import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "sq" | "es" | "fr" | "de" | "it";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translations = getTranslations(language);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

const getTranslations = (lang: Language): Record<string, string> => {
  const translations: Record<Language, Record<string, string>> = {
    en: {
      // Navigation
      "nav.home": "Home",
      "nav.jobs": "Micro-Jobs",
      "nav.regions": "Regions",
      "nav.impact": "Impact",
      "nav.profile": "Profile",
      "auth.login": "Login",
      "auth.signup": "Sign Up",
      "auth.email": "Email",
      "auth.password": "Password",
      "auth.confirmPassword": "Confirm Password",
      "auth.username": "Username",
      "auth.rememberMe": "Remember me",
      "auth.loggingIn": "Logging in...",
      "auth.creatingAccount": "Creating account...",
      "auth.signedIn": "Signed in",
      "auth.logOut": "Log out",
      "auth.signUpFree": "Sign Up Free",
      "common.welcome": "Welcome back!",
      "common.loading": "Loading...",
      "common.save": "Save",
      "common.cancel": "Cancel",
      "common.delete": "Delete",
      "common.edit": "Edit",
      "common.search": "Search",
      "common.saving": "Saving...",
      "common.uploading": "Uploading...",
      "home.badge": "Climate Action Meets Economic Opportunity",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Climate-resilience micro-jobs and learning for vulnerable communities in Europe.",
      "home.welcomeAlert": "Welcome! Sign up or log in to start earning credits and making a climate impact.",
      "home.exploreRegions": "Explore European Regions",
      "home.browseMicroJobs": "Browse Micro-Jobs",
      "home.viewImpact": "View Impact",
      "home.howItWorks": "How GreenWorks CodeX Works",
      "home.feature1.title": "Discover Micro-Jobs",
      "home.feature1.desc": "Browse climate-resilience opportunities across Europe—from tree planting to solar maintenance, tailored to your location and skill level.",
      "home.feature2.title": "Learn & Earn",
      "home.feature2.desc": "Complete micro-learning modules with interactive quizzes. Pass the quiz to unlock job completion and earn credits.",
      "home.feature3.title": "Track Your Impact",
      "home.feature3.desc": "Monitor your earned credits and estimated CO₂ offset on your personal impact dashboard. See your contribution grow.",
      "home.stat1": "Micro-Jobs Available",
      "home.stat2": "European Locations",
      "home.stat3": "kg CO₂ Impact Potential",
      "home.ctaTitle": "Ready to Make an Impact?",
      "home.ctaDescLoggedIn": "Continue your journey towards a more sustainable future while earning economic rewards.",
      "home.ctaDescLoggedOut": "Join GreenWorks CodeX today and start your journey towards a more sustainable future while earning economic rewards.",
      "home.browseAvailableJobs": "Browse Available Jobs",
      "home.exploreRegionsBtn": "Explore Regions",
      "jobs.title": "Climate Micro-Jobs",
      "jobs.subtitle": "Discover opportunities to build climate resilience and earn rewards",
      "jobs.allCategories": "All Categories",
      "jobs.treePlanting": "Tree Planting",
      "jobs.solarMaintenance": "Solar Maintenance",
      "jobs.waterHarvesting": "Water Harvesting",
      "jobs.agroforestry": "Agroforestry",
      "jobs.homeInsulation": "Home Insulation",
      "jobs.allLevels": "All Levels",
      "jobs.beginner": "Beginner",
      "jobs.intermediate": "Intermediate",
      "jobs.advanced": "Advanced",
      "jobs.showing": "Showing",
      "jobs.of": "of",
      "jobs.jobsText": "jobs",
      "jobs.time": "Time",
      "jobs.minutes": "minutes",
      "jobs.credits": "credits",
      "jobs.climateImpact": "Climate impact",
      "jobs.viewDetails": "View Details & Training",
      "jobs.noMatch": "No jobs match your filters. Try adjusting them.",
      "profile.title": "Profile Settings",
      "profile.subtitle": "Manage your account information and preferences",
      "profile.jobsCompleted": "Jobs Completed",
      "profile.creditsEarned": "Credits Earned",
      "profile.co2Impact": "kg CO₂ Impact",
      "profile.profileInfo": "Profile Information",
      "profile.profileDesc": "Update your username and avatar to personalize your account",
      "profile.profilePicture": "Profile Picture",
      "profile.uploadImage": "Upload an image (max 2MB)",
      "profile.uploadBtn": "Upload Image",
      "profile.emailCannotChange": "Your email address cannot be changed",
      "profile.usernameRule": "3-20 characters, letters, numbers, underscores and hyphens only",
      "profile.saveChanges": "Save Changes",
      "impact.title": "Your Impact Dashboard",
      "impact.subtitle": "Track your contribution to climate resilience",
      "impact.disclaimer": "Our prototype simulates how climate-resilience micro-jobs can generate both economic and climate benefits. In a real deployment, each completion would correspond to verified field activity.",
      "impact.jobsCompleted": "Jobs Completed",
      "impact.microJobsFinished": "Micro-jobs finished",
      "impact.totalCredits": "Total Credits",
      "impact.creditsEarned": "Credits earned",
      "impact.co2Impact": "CO₂ Impact",
      "impact.estimatedOffset": "Estimated offset",
      "impact.avgQuizScore": "Avg Quiz Score",
      "impact.learningPerformance": "Learning performance",
      "impact.creditsByCategory": "Credits by Category",
      "impact.creditsDesc": "Total credits earned per job category",
      "impact.co2ByCategory": "CO₂ Impact by Category",
      "impact.co2Desc": "Distribution of your climate impact",
      "impact.recentCompletions": "Recent Completions",
      "impact.recentDesc": "Your latest micro-job achievements",
      "impact.completed": "Completed",
      "impact.score": "score",
      "impact.noImpact": "No Impact Yet",
      "impact.noImpactDesc": "Start completing micro-jobs to see your impact here!",
      "regions.title": "European Priority Regions",
      "regions.subtitle": "Regions ranked by climate need and inequality scores to maximize micro-job impact",
      "regions.regionName": "Region Name",
      "regions.country": "Country",
      "regions.climateNeed": "Climate Need",
      "regions.inequality": "Inequality",
      "regions.priorityScore": "Priority Score",
      "regions.recommendedCategory": "Recommended Category",
      "regions.actions": "Actions",
      "regions.viewDetails": "View Details",
      "regions.noData": "No regions data available.",
      "regions.loadError": "Failed to load regions",
      "regions.high": "High",
      "regions.medium": "Medium",
      "regions.low": "Low",
      "auth.appName": "GreenWorks CodeX",
      "auth.appDescription": "Sign in to track your climate-resilience contributions",
      "auth.minChars": "Minimum 6 characters",
      "auth.passwordsNoMatch": "Passwords don't match",
      "jobDetail.location": "Location",
      "jobDetail.duration": "Duration",
      "jobDetail.reward": "Reward",
      "jobDetail.co2Impact": "CO₂ Impact",
      "jobDetail.min": "min",
      "jobDetail.kg": "kg",
      "jobDetail.learning": "Learning",
      "jobDetail.learningDesc": "Complete this training before taking the quiz",
      "jobDetail.learningObjectives": "Learning Objectives:",
      "jobDetail.knowledgeQuiz": "Knowledge Quiz",
      "jobDetail.quizDesc": "Pass with 60% or higher to complete this micro-job",
      "jobDetail.submitQuiz": "Submit Quiz",
      "jobDetail.passed": "Passed! You can complete this job.",
      "jobDetail.notPassed": "Not quite there. Review the training and try again.",
      "jobDetail.completingJob": "Completing Job...",
      "jobDetail.completeJob": "Complete Job & Earn",
      "jobDetail.retryQuiz": "Retry Quiz",
      "jobDetail.jobNotFound": "Job not found",
      "regionDetail.backToRegions": "Back to Regions",
      "regionDetail.coordinates": "Coordinates",
      "regionDetail.priority": "Priority",
      "regionDetail.aboutPriority": "About Priority Scores: This region's priority score combines climate need and inequality to guide where climate-resilience micro-jobs can have the highest impact. Higher scores indicate areas where interventions can create the most significant positive change for vulnerable communities facing climate challenges.",
      "regionDetail.impactScores": "Impact Scores",
      "regionDetail.impactScoresDesc": "Assessment of climate need and social inequality",
      "regionDetail.climateNeed": "Climate Need",
      "regionDetail.inequality": "Inequality",
      "regionDetail.priorityScore": "Priority Score",
      "regionDetail.networkInfo": "Network Information",
      "regionDetail.avgDownload": "Avg Download",
      "regionDetail.avgUpload": "Avg Upload",
      "regionDetail.latency": "Latency",
      "regionDetail.networkType": "Network Type",
      "regionDetail.landCover": "Land Cover",
      "regionDetail.landCoverDesc": "Dominant landscape type",
      "regionDetail.primaryClass": "Primary land classification",
      "regionDetail.recommendedJobs": "Recommended Micro-Jobs",
      "regionDetail.recommendedJobsDesc": "Most impactful category for this region",
      "regionDetail.viewRecommended": "View Recommended Micro-Jobs",
      "regionDetail.dataSources": "Data Sources",
      "regionDetail.connectivityMetrics": "Connectivity Metrics",
      "regionDetail.connectivityDesc": "providing real-world network performance data including download/upload speeds and latency measurements.",
      "regionDetail.landCoverClass": "Land Cover Classification",
      "regionDetail.landCoverClassDesc": "offering detailed 9-class land-cover analysis to understand regional landscape characteristics.",
      "regionDetail.availableJobs": "Micro-Jobs",
      "regionDetail.availableJobsDesc": "Jobs in this category are recommended for maximum impact in this region",
    },
    sq: {
      "nav.home": "Ballina",
      "nav.jobs": "Mikro-Punët",
      "nav.regions": "Rajonet",
      "nav.impact": "Ndikimi",
      "nav.profile": "Profili",
      "auth.login": "Hyrje",
      "auth.signup": "Regjistrohu",
      "auth.email": "Email",
      "auth.password": "Fjalëkalimi",
      "auth.confirmPassword": "Konfirmo Fjalëkalimin",
      "auth.username": "Emri i përdoruesit",
      "auth.rememberMe": "Më kujto",
      "auth.loggingIn": "Duke u futur...",
      "auth.creatingAccount": "Duke krijuar llogarinë...",
      "auth.signedIn": "I kyqur",
      "auth.logOut": "Dil",
      "auth.signUpFree": "Regjistrohu Falas",
      "common.welcome": "Mirë se erdhe përsëri!",
      "common.loading": "Duke u ngarkuar...",
      "common.save": "Ruaj",
      "common.cancel": "Anulo",
      "common.delete": "Fshi",
      "common.edit": "Ndrysho",
      "common.search": "Kërko",
      "common.saving": "Duke ruajtur...",
      "common.uploading": "Duke ngarkuar...",
      "home.badge": "Veprimi Klimatik Takohet me Mundësinë Ekonomike",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Mikro-punë dhe mësim për qëndrueshmërinë klimatike për komunitetet e cenueshme në Evropë.",
      "home.welcomeAlert": "Mirë se vini! Regjistrohuni ose hyni për të filluar të fitoni kredite dhe të bëni ndikim klimatik.",
      "home.exploreRegions": "Eksploro Rajonet Evropiane",
      "home.browseMicroJobs": "Shfleto Mikro-Punët",
      "home.viewImpact": "Shiko Ndikimin",
      "home.howItWorks": "Si Funksionon GreenWorks CodeX",
      "home.feature1.title": "Zbullo Mikro-Punët",
      "home.feature1.desc": "Shfleto mundësitë për qëndrueshmëri klimatike në të gjithë Evropën—nga mbjellja e pemëve tek mirëmbajtja diellore, të përshtatura për vendndodhjen dhe nivelin tënd të aftësive.",
      "home.feature2.title": "Mëso & Fito",
      "home.feature2.desc": "Plotëso module mikro-mësimi me kuize interaktive. Kalo kuizin për të zhbllokuar përfundimin e punës dhe për të fituar kredite.",
      "home.feature3.title": "Gjurmo Ndikimin Tënd",
      "home.feature3.desc": "Monitoroni kreditë tuaja të fituara dhe kompenimin e përllogaritur të CO₂ në panelin tuaj personal të ndikimit. Shihni kontributin tuaj të rritet.",
      "home.stat1": "Mikro-Punë të Disponueshme",
      "home.stat2": "Vendndodhje Evropiane",
      "home.stat3": "kg Potencial Ndikimi CO₂",
      "home.ctaTitle": "Gati për të Bërë Ndikim?",
      "home.ctaDescLoggedIn": "Vazhdo udhëtimin tënd drejt një të ardhmeje më të qëndrueshme duke fituar shpërblime ekonomike.",
      "home.ctaDescLoggedOut": "Bashkohuni me GreenWorks CodeX sot dhe filloni udhëtimin tuaj drejt një të ardhmeje më të qëndrueshme duke fituar shpërblime ekonomike.",
      "home.browseAvailableJobs": "Shfleto Punët e Disponueshme",
      "home.exploreRegionsBtn": "Eksploro Rajonet",
      "jobs.title": "Mikro-Punë Klimatike",
      "jobs.subtitle": "Zbullo mundësi për të ndërtuar qëndrueshmëri klimatike dhe për të fituar shpërblime",
      "jobs.allCategories": "Të Gjitha Kategoritë",
      "jobs.treePlanting": "Mbjell je Pemësh",
      "jobs.solarMaintenance": "Mirëmbajtje Diellore",
      "jobs.waterHarvesting": "Grumbullim i Ujit",
      "jobs.agroforestry": "Agropylltari",
      "jobs.homeInsulation": "Izolim i Shtëpisë",
      "jobs.allLevels": "Të Gjitha Nivelet",
      "jobs.beginner": "Fillestar",
      "jobs.intermediate": "Mesatar",
      "jobs.advanced": "I Avancuar",
      "jobs.showing": "Duke treguar",
      "jobs.of": "nga",
      "jobs.jobsText": "punë",
      "jobs.time": "Kohëzgjatja",
      "jobs.minutes": "minuta",
      "jobs.credits": "kredite",
      "jobs.climateImpact": "Ndikimi klimatik",
      "jobs.viewDetails": "Shiko Detajet & Trajnimin",
      "jobs.noMatch": "Asnjë punë nuk përputhet me filtrat tuaj. Provo t'i rregullosh ato.",
      "profile.title": "Cilësimet e Profilit",
      "profile.subtitle": "Menaxho informacionin e llogarisë dhe preferencat",
      "profile.jobsCompleted": "Punë të Përfunduara",
      "profile.creditsEarned": "Kredite të Fituara",
      "profile.co2Impact": "kg Ndikim CO₂",
      "profile.profileInfo": "Informacioni i Profilit",
      "profile.profileDesc": "Përditëso emrin e përdoruesit dhe avatarin për të personalizuar llogarinë",
      "profile.profilePicture": "Fotografia e Profilit",
      "profile.uploadImage": "Ngarko një imazh (maks 2MB)",
      "profile.uploadBtn": "Ngarko Imazhin",
      "profile.emailCannotChange": "Adresa juaj e emailit nuk mund të ndryshohet",
      "profile.usernameRule": "3-20 karaktere, vetëm shkronja, numra, nënviza dhe viza",
      "profile.saveChanges": "Ruaj Ndryshimet",
      "impact.title": "Paneli Juaj i Ndikimit",
      "impact.subtitle": "Gjurmoni kontributin tuaj për qëndrueshmërinë klimatike",
      "impact.disclaimer": "Prototipi ynë simulon se si mikro-punët e qëndrueshmërisë klimatike mund të gjenerojnë përfitime ekonomike dhe klimatike. Në një aplikim real, çdo përfundim do të korrespondonte me aktivitet të verifikuar në terren.",
      "impact.jobsCompleted": "Punë të Përfunduara",
      "impact.microJobsFinished": "Mikro-punë të përfunduara",
      "impact.totalCredits": "Kredite Totale",
      "impact.creditsEarned": "Kredite të fituara",
      "impact.co2Impact": "Ndikimi CO₂",
      "impact.estimatedOffset": "Kompensim i përllogaritur",
      "impact.avgQuizScore": "Rezultat Mesatar Kuizi",
      "impact.learningPerformance": "Performanca e të mësuarit",
      "impact.creditsByCategory": "Kredite sipas Kategorisë",
      "impact.creditsDesc": "Totali i krediteve të fituara për kategori pune",
      "impact.co2ByCategory": "Ndikimi CO₂ sipas Kategorisë",
      "impact.co2Desc": "Shpërndarja e ndikimit tuaj klimatik",
      "impact.recentCompletions": "Përfundimet e Fundit",
      "impact.recentDesc": "Arritjet tuaja më të fundit në mikro-punë",
      "impact.completed": "U përfundua",
      "impact.score": "rezultat",
      "impact.noImpact": "Ende Pa Ndikim",
      "impact.noImpactDesc": "Filloni të përfundoni mikro-punë për të parë ndikimin tuaj këtu!",
      "regions.title": "Rajonet Prioritare Evropiane",
      "regions.subtitle": "Rajonet e renditura sipas nevojës klimatike dhe rezultateve të pabarazisë për të maksimizuar ndikimin e mikro-punëve",
      "regions.regionName": "Emri i Rajonit",
      "regions.country": "Shteti",
      "regions.climateNeed": "Nevoja Klimatike",
      "regions.inequality": "Pabarazia",
      "regions.priorityScore": "Rezultati i Prioritetit",
      "regions.recommendedCategory": "Kategoria e Rekomanduar",
      "regions.actions": "Veprimet",
      "regions.viewDetails": "Shiko Detajet",
      "regions.noData": "Nuk ka të dhëna të rajoneve.",
      "regions.loadError": "Dështoi ngarkimi i rajoneve",
      "regions.high": "I Lartë",
      "regions.medium": "Mesatar",
      "regions.low": "I Ulët",
      "auth.appName": "GreenWorks CodeX",
      "auth.appDescription": "Hyni për të gjurmuar kontributet tuaja për qëndrueshmërinë klimatike",
      "auth.minChars": "Minimum 6 karaktere",
      "auth.passwordsNoMatch": "Fjalëkalimet nuk përputhen",
      "jobDetail.location": "Vendndodhja",
      "jobDetail.duration": "Kohëzgjatja",
      "jobDetail.reward": "Shpërblimi",
      "jobDetail.co2Impact": "Ndikimi CO₂",
      "jobDetail.min": "min",
      "jobDetail.kg": "kg",
      "jobDetail.learning": "Mësimi",
      "jobDetail.learningDesc": "Plotësoni këtë trajnim para se të merrni kuizin",
      "jobDetail.learningObjectives": "Objektivat e Mësimit:",
      "jobDetail.knowledgeQuiz": "Kuizi i Njohurive",
      "jobDetail.quizDesc": "Kaloni me 60% ose më shumë për të përfunduar këtë mikro-punë",
      "jobDetail.submitQuiz": "Dërgo Kuizin",
      "jobDetail.passed": "Kaluar! Ju mund të përfundoni këtë punë.",
      "jobDetail.notPassed": "Ende jo. Rishikoni trajnimin dhe provoni përsëri.",
      "jobDetail.completingJob": "Duke përfunduar punën...",
      "jobDetail.completeJob": "Përfundo Punën & Fito",
      "jobDetail.retryQuiz": "Riprovo Kuizin",
      "jobDetail.jobNotFound": "Puna nuk u gjet",
      "regionDetail.backToRegions": "Kthehu tek Rajonet",
      "regionDetail.coordinates": "Koordinatat",
      "regionDetail.priority": "Prioriteti",
      "regionDetail.aboutPriority": "Rreth Rezultateve të Prioritetit: Rezultati i prioritetit të kësaj rajoni kombinon nevojën klimatike dhe pabarazinë për të udhëzuar se ku mikro-punët e qëndrueshmërisë klimatike mund të kenë ndikimin më të lartë. Rezultate më të larta tregojnë zona ku ndërhyrjet mund të krijojnë ndryshimin pozitiv më të rëndësishëm për komunitetet e cenueshme që përballen me sfida klimatike.",
      "regionDetail.impactScores": "Rezultatet e Ndikimit",
      "regionDetail.impactScoresDesc": "Vlerësimi i nevojës klimatike dhe pabarazisë sociale",
      "regionDetail.climateNeed": "Nevoja Klimatike",
      "regionDetail.inequality": "Pabarazia",
      "regionDetail.priorityScore": "Rezultati i Prioritetit",
      "regionDetail.networkInfo": "Informacioni i Rrjetit",
      "regionDetail.avgDownload": "Shkarkimi Mesatar",
      "regionDetail.avgUpload": "Ngarkimi Mesatar",
      "regionDetail.latency": "Vonesë",
      "regionDetail.networkType": "Lloji i Rrjetit",
      "regionDetail.landCover": "Mbulesa e Tokës",
      "regionDetail.landCoverDesc": "Lloji dominant i peizazhit",
      "regionDetail.primaryClass": "Klasifikimi primar i tokës",
      "regionDetail.recommendedJobs": "Mikro-Punë të Rekomanduara",
      "regionDetail.recommendedJobsDesc": "Kategoria më me ndikim për këtë rajon",
      "regionDetail.viewRecommended": "Shiko Mikro-Punët e Rekomanduara",
      "regionDetail.dataSources": "Burimet e të Dhënave",
      "regionDetail.connectivityMetrics": "Metrikat e Lidhjes",
      "regionDetail.connectivityDesc": "duke ofruar të dhëna të performancës së rrjetit në botën reale, duke përfshirë shpejtësitë e shkarkimit/ngarkimit dhe matjet e vonesës.",
      "regionDetail.landCoverClass": "Klasifikimi i Mbulimit të Tokës",
      "regionDetail.landCoverClassDesc": "duke ofruar analizë të detajuar me 9 klasa të mbulimit të tokës për të kuptuar karakteristikat e peizazhit rajonal.",
      "regionDetail.availableJobs": "Mikro-Punë",
      "regionDetail.availableJobsDesc": "Punët në këtë kategori rekomandon për ndikim maksimal në këtë rajon",
    },
    es: {
      // Navigation (Spanish)
      "nav.home": "Inicio",
      "nav.jobs": "Micro-Trabajos",
      "nav.regions": "Regiones",
      "nav.impact": "Impacto",
      "nav.profile": "Perfil",
      "auth.login": "Iniciar sesión",
      "auth.signup": "Registrarse",
      "auth.email": "Correo electrónico",
      "auth.password": "Contraseña",
      "auth.confirmPassword": "Confirmar contraseña",
      "auth.username": "Nombre de usuario",
      "auth.rememberMe": "Recuérdame",
      "auth.loggingIn": "Iniciando sesión...",
      "auth.creatingAccount": "Creando cuenta...",
      "auth.signedIn": "Sesión iniciada",
      "auth.logOut": "Cerrar sesión",
      "auth.signUpFree": "Registrarse Gratis",
      "common.welcome": "¡Bienvenido de nuevo!",
      "common.loading": "Cargando...",
      "common.save": "Guardar",
      "common.cancel": "Cancelar",
      "common.delete": "Eliminar",
      "common.edit": "Editar",
      "common.search": "Buscar",
      "common.saving": "Guardando...",
      "common.uploading": "Subiendo...",
      "home.badge": "Acción Climática se Encuentra con Oportunidad Económica",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Micro-trabajos y aprendizaje de resiliencia climática para comunidades vulnerables en Europa.",
      "home.welcomeAlert": "¡Bienvenido! Regístrate o inicia sesión para comenzar a ganar créditos y hacer un impacto climático.",
      "home.exploreRegions": "Explorar Regiones Europeas",
      "home.browseMicroJobs": "Navegar Micro-Trabajos",
      "home.viewImpact": "Ver Impacto",
      "home.howItWorks": "Cómo Funciona GreenWorks CodeX",
      "home.feature1.title": "Descubre Micro-Trabajos",
      "home.feature1.desc": "Explora oportunidades de resiliencia climática en Europa, desde plantar árboles hasta mantenimiento solar, adaptadas a tu ubicación y nivel de habilidad.",
      "home.feature2.title": "Aprende & Gana",
      "home.feature2.desc": "Completa módulos de micro-aprendizaje con cuestionarios interactivos. Aprueba el cuestionario para desbloquear la finalización del trabajo y ganar créditos.",
      "home.feature3.title": "Rastrea Tu Impacto",
      "home.feature3.desc": "Monitorea tus créditos ganados y la compensación estimada de CO₂ en tu panel de impacto personal. Ve crecer tu contribución.",
      "home.stat1": "Micro-Trabajos Disponibles",
      "home.stat2": "Ubicaciones Europeas",
      "home.stat3": "kg de Potencial de Impacto CO₂",
      "home.ctaTitle": "¿Listo para Hacer un Impacto?",
      "home.ctaDescLoggedIn": "Continúa tu viaje hacia un futuro más sostenible mientras ganas recompensas económicas.",
      "home.ctaDescLoggedOut": "Únete a GreenWorks CodeX hoy y comienza tu viaje hacia un futuro más sostenible mientras ganas recompensas económicas.",
      "home.browseAvailableJobs": "Navegar Trabajos Disponibles",
      "home.exploreRegionsBtn": "Explorar Regiones",
      "jobs.title": "Micro-Trabajos Climáticos",
      "jobs.subtitle": "Descubre oportunidades para construir resiliencia climática y ganar recompensas",
      "jobs.allCategories": "Todas las Categorías",
      "jobs.treePlanting": "Plantación de Árboles",
      "jobs.solarMaintenance": "Mantenimiento Solar",
      "jobs.waterHarvesting": "Recolección de Agua",
      "jobs.agroforestry": "Agroforestería",
      "jobs.homeInsulation": "Aislamiento del Hogar",
      "jobs.allLevels": "Todos los Niveles",
      "jobs.beginner": "Principiante",
      "jobs.intermediate": "Intermedio",
      "jobs.advanced": "Avanzado",
      "jobs.showing": "Mostrando",
      "jobs.of": "de",
      "jobs.jobsText": "trabajos",
      "jobs.time": "Tiempo",
      "jobs.minutes": "minutos",
      "jobs.credits": "créditos",
      "jobs.climateImpact": "Impacto climático",
      "jobs.viewDetails": "Ver Detalles y Capacitación",
      "jobs.noMatch": "Ningún trabajo coincide con tus filtros. Intenta ajustarlos.",
      "profile.title": "Configuración del Perfil",
      "profile.subtitle": "Gestiona la información de tu cuenta y preferencias",
      "profile.jobsCompleted": "Trabajos Completados",
      "profile.creditsEarned": "Créditos Ganados",
      "profile.co2Impact": "kg de Impacto CO₂",
      "profile.profileInfo": "Información del Perfil",
      "profile.profileDesc": "Actualiza tu nombre de usuario y avatar para personalizar tu cuenta",
      "profile.profilePicture": "Foto de Perfil",
      "profile.uploadImage": "Sube una imagen (máx 2MB)",
      "profile.uploadBtn": "Subir Imagen",
      "profile.emailCannotChange": "Tu dirección de correo electrónico no se puede cambiar",
      "profile.usernameRule": "3-20 caracteres, solo letras, números, guiones bajos y guiones",
      "profile.saveChanges": "Guardar Cambios",
      "impact.title": "Tu Panel de Impacto",
      "impact.subtitle": "Rastrea tu contribución a la resiliencia climática",
      "impact.disclaimer": "Nuestro prototipo simula cómo los micro-trabajos de resiliencia climática pueden generar beneficios económicos y climáticos. En una implementación real, cada finalización correspondería a actividad verificada en campo.",
      "impact.jobsCompleted": "Trabajos Completados",
      "impact.microJobsFinished": "Micro-trabajos terminados",
      "impact.totalCredits": "Créditos Totales",
      "impact.creditsEarned": "Créditos ganados",
      "impact.co2Impact": "Impacto CO₂",
      "impact.estimatedOffset": "Compensación estimada",
      "impact.avgQuizScore": "Puntuación Promedio del Cuestionario",
      "impact.learningPerformance": "Rendimiento de aprendizaje",
      "impact.creditsByCategory": "Créditos por Categoría",
      "impact.creditsDesc": "Total de créditos ganados por categoría de trabajo",
      "impact.co2ByCategory": "Impacto CO₂ por Categoría",
      "impact.co2Desc": "Distribución de tu impacto climático",
      "impact.recentCompletions": "Finalizaciones Recientes",
      "impact.recentDesc": "Tus últimos logros en micro-trabajos",
      "impact.completed": "Completado",
      "impact.score": "puntuación",
      "impact.noImpact": "Aún Sin Impacto",
      "impact.noImpactDesc": "¡Comienza a completar micro-trabajos para ver tu impacto aquí!",
      "regions.title": "Regiones Prioritarias Europeas",
      "regions.subtitle": "Regiones clasificadas por necesidad climática y puntuaciones de desigualdad para maximizar el impacto de los micro-trabajos",
      "regions.regionName": "Nombre de la Región",
      "regions.country": "País",
      "regions.climateNeed": "Necesidad Climática",
      "regions.inequality": "Desigualdad",
      "regions.priorityScore": "Puntuación de Prioridad",
      "regions.recommendedCategory": "Categoría Recomendada",
      "regions.actions": "Acciones",
      "regions.viewDetails": "Ver Detalles",
      "regions.noData": "No hay datos de regiones disponibles.",
      "regions.loadError": "Error al cargar regiones",
      "regions.high": "Alta",
      "regions.medium": "Media",
      "regions.low": "Baja",
      "auth.appName": "GreenWorks CodeX",
      "auth.appDescription": "Inicia sesión para rastrear tus contribuciones a la resiliencia climática",
      "auth.minChars": "Mínimo 6 caracteres",
      "auth.passwordsNoMatch": "Las contraseñas no coinciden",
      "jobDetail.location": "Ubicación",
      "jobDetail.duration": "Duración",
      "jobDetail.reward": "Recompensa",
      "jobDetail.co2Impact": "Impacto CO₂",
      "jobDetail.min": "min",
      "jobDetail.kg": "kg",
      "jobDetail.learning": "Aprendizaje",
      "jobDetail.learningDesc": "Completa esta capacitación antes de tomar el cuestionario",
      "jobDetail.learningObjectives": "Objetivos de Aprendizaje:",
      "jobDetail.knowledgeQuiz": "Cuestionario de Conocimiento",
      "jobDetail.quizDesc": "Aprueba con 60% o más para completar este micro-trabajo",
      "jobDetail.submitQuiz": "Enviar Cuestionario",
      "jobDetail.passed": "¡Aprobado! Puedes completar este trabajo.",
      "jobDetail.notPassed": "Aún no. Revisa la capacitación e intenta de nuevo.",
      "jobDetail.completingJob": "Completando trabajo...",
      "jobDetail.completeJob": "Completar Trabajo y Ganar",
      "jobDetail.retryQuiz": "Reintentar Cuestionario",
      "jobDetail.jobNotFound": "Trabajo no encontrado",
      "regionDetail.backToRegions": "Volver a Regiones",
      "regionDetail.coordinates": "Coordenadas",
      "regionDetail.priority": "Prioridad",
      "regionDetail.aboutPriority": "Acerca de las Puntuaciones de Prioridad: La puntuación de prioridad de esta región combina la necesidad climática y la desigualdad para guiar dónde los micro-trabajos de resiliencia climática pueden tener el mayor impacto. Puntuaciones más altas indican áreas donde las intervenciones pueden crear el cambio positivo más significativo para las comunidades vulnerables que enfrentan desafíos climáticos.",
      "regionDetail.impactScores": "Puntuaciones de Impacto",
      "regionDetail.impactScoresDesc": "Evaluación de necesidad climática y desigualdad social",
      "regionDetail.climateNeed": "Necesidad Climática",
      "regionDetail.inequality": "Desigualdad",
      "regionDetail.priorityScore": "Puntuación de Prioridad",
      "regionDetail.networkInfo": "Información de Red",
      "regionDetail.avgDownload": "Descarga Promedio",
      "regionDetail.avgUpload": "Carga Promedio",
      "regionDetail.latency": "Latencia",
      "regionDetail.networkType": "Tipo de Red",
      "regionDetail.landCover": "Cobertura del Suelo",
      "regionDetail.landCoverDesc": "Tipo de paisaje dominante",
      "regionDetail.primaryClass": "Clasificación primaria del suelo",
      "regionDetail.recommendedJobs": "Micro-Trabajos Recomendados",
      "regionDetail.recommendedJobsDesc": "Categoría de mayor impacto para esta región",
      "regionDetail.viewRecommended": "Ver Micro-Trabajos Recomendados",
      "regionDetail.dataSources": "Fuentes de Datos",
      "regionDetail.connectivityMetrics": "Métricas de Conectividad",
      "regionDetail.connectivityDesc": "proporcionando datos de rendimiento de red del mundo real incluyendo velocidades de descarga/carga y mediciones de latencia.",
      "regionDetail.landCoverClass": "Clasificación de Cobertura del Suelo",
      "regionDetail.landCoverClassDesc": "ofreciendo análisis detallado de cobertura del suelo de 9 clases para comprender las características del paisaje regional.",
      "regionDetail.availableJobs": "Micro-Trabajos",
      "regionDetail.availableJobsDesc": "Los trabajos en esta categoría son recomendados para máximo impacto en esta región",
    },
    fr: {
      // Navigation (French)
      "nav.home": "Accueil",
      "nav.jobs": "Micro-Emplois",
      "nav.regions": "Régions",
      "nav.impact": "Impact",
      "nav.profile": "Profil",
      "auth.login": "Connexion",
      "auth.signup": "S'inscrire",
      "auth.email": "Email",
      "auth.password": "Mot de passe",
      "auth.confirmPassword": "Confirmer le mot de passe",
      "auth.username": "Nom d'utilisateur",
      "auth.rememberMe": "Se souvenir de moi",
      "auth.loggingIn": "Connexion en cours...",
      "auth.creatingAccount": "Création du compte...",
      "auth.signedIn": "Connecté",
      "auth.logOut": "Se déconnecter",
      "auth.signUpFree": "S'inscrire Gratuitement",
      "common.welcome": "Bon retour!",
      "common.loading": "Chargement...",
      "common.save": "Enregistrer",
      "common.cancel": "Annuler",
      "common.delete": "Supprimer",
      "common.edit": "Modifier",
      "common.search": "Rechercher",
      "common.saving": "Enregistrement...",
      "common.uploading": "Téléchargement...",
      "home.badge": "L'action Climatique Rencontre l'Opportunité Économique",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Micro-emplois et apprentissage de résilience climatique pour les communautés vulnérables en Europe.",
      "home.welcomeAlert": "Bienvenue! Inscrivez-vous ou connectez-vous pour commencer à gagner des crédits et avoir un impact climatique.",
      "home.exploreRegions": "Explorer les Régions Européennes",
      "home.browseMicroJobs": "Parcourir les Micro-Emplois",
      "home.viewImpact": "Voir l'Impact",
      "home.howItWorks": "Comment Fonctionne GreenWorks CodeX",
      "home.feature1.title": "Découvrir les Micro-Emplois",
      "home.feature1.desc": "Parcourez les opportunités de résilience climatique en Europe—de la plantation d'arbres à l'entretien solaire, adaptées à votre emplacement et niveau de compétence.",
      "home.feature2.title": "Apprendre & Gagner",
      "home.feature2.desc": "Complétez des modules de micro-apprentissage avec des quiz interactifs. Réussissez le quiz pour déverrouiller l'achèvement du travail et gagner des crédits.",
      "home.feature3.title": "Suivre Votre Impact",
      "home.feature3.desc": "Surveillez vos crédits gagnés et la compensation estimée en CO₂ sur votre tableau de bord d'impact personnel. Voyez votre contribution grandir.",
      "home.stat1": "Micro-Emplois Disponibles",
      "home.stat2": "Emplacements Européens",
      "home.stat3": "kg de Potentiel d'Impact CO₂",
      "home.ctaTitle": "Prêt à Faire un Impact?",
      "home.ctaDescLoggedIn": "Continuez votre voyage vers un avenir plus durable tout en gagnant des récompenses économiques.",
      "home.ctaDescLoggedOut": "Rejoignez GreenWorks CodeX aujourd'hui et commencez votre voyage vers un avenir plus durable tout en gagnant des récompenses économiques.",
      "home.browseAvailableJobs": "Parcourir les Emplois Disponibles",
      "home.exploreRegionsBtn": "Explorer les Régions",
      "jobs.title": "Micro-Emplois Climatiques",
      "jobs.subtitle": "Découvrez des opportunités pour bâtir la résilience climatique et gagner des récompenses",
      "jobs.allCategories": "Toutes les Catégories",
      "jobs.treePlanting": "Plantation d'Arbres",
      "jobs.solarMaintenance": "Entretien Solaire",
      "jobs.waterHarvesting": "Collecte d'Eau",
      "jobs.agroforestry": "Agroforesterie",
      "jobs.homeInsulation": "Isolation de la Maison",
      "jobs.allLevels": "Tous les Niveaux",
      "jobs.beginner": "Débutant",
      "jobs.intermediate": "Intermédiaire",
      "jobs.advanced": "Avancé",
      "jobs.showing": "Affichage",
      "jobs.of": "de",
      "jobs.jobsText": "emplois",
      "jobs.time": "Durée",
      "jobs.minutes": "minutes",
      "jobs.credits": "crédits",
      "jobs.climateImpact": "Impact climatique",
      "jobs.viewDetails": "Voir Détails et Formation",
      "jobs.noMatch": "Aucun emploi ne correspond à vos filtres. Essayez de les ajuster.",
      "profile.title": "Paramètres du Profil",
      "profile.subtitle": "Gérez les informations de votre compte et vos préférences",
      "profile.jobsCompleted": "Emplois Terminés",
      "profile.creditsEarned": "Crédits Gagnés",
      "profile.co2Impact": "kg d'Impact CO₂",
      "profile.profileInfo": "Informations du Profil",
      "profile.profileDesc": "Mettez à jour votre nom d'utilisateur et votre avatar pour personnaliser votre compte",
      "profile.profilePicture": "Photo de Profil",
      "profile.uploadImage": "Télécharger une image (max 2 Mo)",
      "profile.uploadBtn": "Télécharger l'Image",
      "profile.emailCannotChange": "Votre adresse e-mail ne peut pas être modifiée",
      "profile.usernameRule": "3-20 caractères, lettres, chiffres, tirets bas et traits d'union uniquement",
      "profile.saveChanges": "Enregistrer les Modifications",
      "impact.title": "Votre Tableau de Bord d'Impact",
      "impact.subtitle": "Suivez votre contribution à la résilience climatique",
      "impact.disclaimer": "Notre prototype simule comment les micro-emplois de résilience climatique peuvent générer à la fois des avantages économiques et climatiques. Dans un déploiement réel, chaque achèvement correspondrait à une activité vérifiée sur le terrain.",
      "impact.jobsCompleted": "Emplois Terminés",
      "impact.microJobsFinished": "Micro-emplois terminés",
      "impact.totalCredits": "Crédits Totaux",
      "impact.creditsEarned": "Crédits gagnés",
      "impact.co2Impact": "Impact CO₂",
      "impact.estimatedOffset": "Compensation estimée",
      "impact.avgQuizScore": "Score Moyen du Quiz",
      "impact.learningPerformance": "Performance d'apprentissage",
      "impact.creditsByCategory": "Crédits par Catégorie",
      "impact.creditsDesc": "Total des crédits gagnés par catégorie d'emploi",
      "impact.co2ByCategory": "Impact CO₂ par Catégorie",
      "impact.co2Desc": "Distribution de votre impact climatique",
      "impact.recentCompletions": "Achèvements Récents",
      "impact.recentDesc": "Vos dernières réalisations en micro-emplois",
      "impact.completed": "Terminé",
      "impact.score": "score",
      "impact.noImpact": "Pas Encore d'Impact",
      "impact.noImpactDesc": "Commencez à terminer des micro-emplois pour voir votre impact ici!",
      "regions.title": "Régions Prioritaires Européennes",
      "regions.subtitle": "Régions classées par besoin climatique et scores d'inégalité pour maximiser l'impact des micro-emplois",
      "regions.regionName": "Nom de la Région",
      "regions.country": "Pays",
      "regions.climateNeed": "Besoin Climatique",
      "regions.inequality": "Inégalité",
      "regions.priorityScore": "Score de Priorité",
      "regions.recommendedCategory": "Catégorie Recommandée",
      "regions.actions": "Actions",
      "regions.viewDetails": "Voir Détails",
      "regions.noData": "Aucune donnée de région disponible.",
      "regions.loadError": "Échec du chargement des régions",
      "regions.high": "Élevé",
      "regions.medium": "Moyen",
      "regions.low": "Faible",
      "auth.appName": "GreenWorks CodeX",
      "auth.appDescription": "Connectez-vous pour suivre vos contributions à la résilience climatique",
      "auth.minChars": "Minimum 6 caractères",
      "auth.passwordsNoMatch": "Les mots de passe ne correspondent pas",
      "jobDetail.location": "Emplacement",
      "jobDetail.duration": "Durée",
      "jobDetail.reward": "Récompense",
      "jobDetail.co2Impact": "Impact CO₂",
      "jobDetail.min": "min",
      "jobDetail.kg": "kg",
      "jobDetail.learning": "Apprentissage",
      "jobDetail.learningDesc": "Complétez cette formation avant de passer le quiz",
      "jobDetail.learningObjectives": "Objectifs d'Apprentissage:",
      "jobDetail.knowledgeQuiz": "Quiz de Connaissances",
      "jobDetail.quizDesc": "Réussissez avec 60% ou plus pour terminer ce micro-emploi",
      "jobDetail.submitQuiz": "Soumettre le Quiz",
      "jobDetail.passed": "Réussi! Vous pouvez terminer ce travail.",
      "jobDetail.notPassed": "Pas tout à fait. Révisez la formation et réessayez.",
      "jobDetail.completingJob": "Achèvement du travail...",
      "jobDetail.completeJob": "Terminer le Travail et Gagner",
      "jobDetail.retryQuiz": "Réessayer le Quiz",
      "jobDetail.jobNotFound": "Travail non trouvé",
      "regionDetail.backToRegions": "Retour aux Régions",
      "regionDetail.coordinates": "Coordonnées",
      "regionDetail.priority": "Priorité",
      "regionDetail.aboutPriority": "À propos des Scores de Priorité: Le score de priorité de cette région combine le besoin climatique et l'inégalité pour guider où les micro-emplois de résilience climatique peuvent avoir le plus grand impact. Des scores plus élevés indiquent les zones où les interventions peuvent créer le changement positif le plus significatif pour les communautés vulnérables confrontées à des défis climatiques.",
      "regionDetail.impactScores": "Scores d'Impact",
      "regionDetail.impactScoresDesc": "Évaluation du besoin climatique et de l'inégalité sociale",
      "regionDetail.climateNeed": "Besoin Climatique",
      "regionDetail.inequality": "Inégalité",
      "regionDetail.priorityScore": "Score de Priorité",
      "regionDetail.networkInfo": "Informations Réseau",
      "regionDetail.avgDownload": "Téléchargement Moyen",
      "regionDetail.avgUpload": "Téléversement Moyen",
      "regionDetail.latency": "Latence",
      "regionDetail.networkType": "Type de Réseau",
      "regionDetail.landCover": "Couverture du Sol",
      "regionDetail.landCoverDesc": "Type de paysage dominant",
      "regionDetail.primaryClass": "Classification primaire des terres",
      "regionDetail.recommendedJobs": "Micro-Emplois Recommandés",
      "regionDetail.recommendedJobsDesc": "Catégorie la plus impactante pour cette région",
      "regionDetail.viewRecommended": "Voir les Micro-Emplois Recommandés",
      "regionDetail.dataSources": "Sources de Données",
      "regionDetail.connectivityMetrics": "Métriques de Connectivité",
      "regionDetail.connectivityDesc": "fournissant des données de performance réseau du monde réel, y compris les vitesses de téléchargement/téléversement et les mesures de latence.",
      "regionDetail.landCoverClass": "Classification de la Couverture du Sol",
      "regionDetail.landCoverClassDesc": "offrant une analyse détaillée de la couverture du sol à 9 classes pour comprendre les caractéristiques du paysage régional.",
      "regionDetail.availableJobs": "Micro-Emplois",
      "regionDetail.availableJobsDesc": "Les emplois de cette catégorie sont recommandés pour un impact maximal dans cette région",
    },
    de: {
      // Navigation (German)
      "nav.home": "Startseite",
      "nav.jobs": "Jobs",
      "nav.regions": "Regionen",
      "nav.impact": "Auswirkung",
      "nav.profile": "Profil",
      "auth.login": "Anmelden",
      "auth.signup": "Registrieren",
      "auth.email": "E-Mail",
      "auth.password": "Passwort",
      "auth.confirmPassword": "Passwort bestätigen",
      "auth.username": "Benutzername",
      "auth.rememberMe": "Erinnere dich an mich",
      "auth.loggingIn": "Anmeldung läuft...",
      "auth.creatingAccount": "Konto wird erstellt...",
      "auth.signedIn": "Angemeldet",
      "auth.logOut": "Abmelden",
      "auth.signUpFree": "Kostenlos Registrieren",
      "common.welcome": "Willkommen zurück!",
      "common.loading": "Wird geladen...",
      "common.save": "Speichern",
      "common.cancel": "Abbrechen",
      "common.delete": "Löschen",
      "common.edit": "Bearbeiten",
      "common.search": "Suchen",
      "common.saving": "Speichern...",
      "common.uploading": "Hochladen...",
      "home.badge": "Klimaschutz Trifft Wirtschaftliche Chancen",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Klimaresilienz-Mikrojobs und Lernen für gefährdete Gemeinden in Europa.",
      "home.welcomeAlert": "Willkommen! Melden Sie sich an oder registrieren Sie sich, um Credits zu verdienen und klimawirksam zu werden.",
      "home.exploreRegions": "Europäische Regionen Erkunden",
      "home.browseMicroJobs": "Mikrojobs Durchsuchen",
      "home.viewImpact": "Auswirkung Anzeigen",
      "home.howItWorks": "So Funktioniert GreenWorks CodeX",
      "home.feature1.title": "Mikrojobs Entdecken",
      "home.feature1.desc": "Durchsuchen Sie Klimaresilienz-Möglichkeiten in ganz Europa—von Baumpflanzungen bis zur Solarpflege, angepasst an Ihren Standort und Ihr Qualifikationsniveau.",
      "home.feature2.title": "Lernen & Verdienen",
      "home.feature2.desc": "Absolvieren Sie Mikro-Lernmodule mit interaktiven Quiz. Bestehen Sie das Quiz, um die Jobabschluss freizuschalten und Credits zu verdienen.",
      "home.feature3.title": "Verfolgen Sie Ihre Auswirkung",
      "home.feature3.desc": "Überwachen Sie Ihre verdienten Credits und geschätzte CO₂-Kompensation auf Ihrem persönlichen Impact-Dashboard. Sehen Sie Ihren Beitrag wachsen.",
      "home.stat1": "Mikrojobs Verfügbar",
      "home.stat2": "Europäische Standorte",
      "home.stat3": "kg CO₂-Auswirkungspotenzial",
      "home.ctaTitle": "Bereit, Wirkung zu Zeigen?",
      "home.ctaDescLoggedIn": "Setzen Sie Ihre Reise zu einer nachhaltigeren Zukunft fort und verdienen Sie wirtschaftliche Belohnungen.",
      "home.ctaDescLoggedOut": "Treten Sie GreenWorks CodeX heute bei und beginnen Sie Ihre Reise zu einer nachhaltigeren Zukunft, während Sie wirtschaftliche Belohnungen verdienen.",
      "home.browseAvailableJobs": "Verfügbare Jobs Durchsuchen",
      "home.exploreRegionsBtn": "Regionen Erkunden",
      "jobs.title": "Klima-Mikrojobs",
      "jobs.subtitle": "Entdecken Sie Möglichkeiten, Klimaresilienz aufzubauen und Belohnungen zu verdienen",
      "jobs.allCategories": "Alle Kategorien",
      "jobs.treePlanting": "Baumpflanzung",
      "jobs.solarMaintenance": "Solarwartung",
      "jobs.waterHarvesting": "Wassergewinnung",
      "jobs.agroforestry": "Agroforstwirtschaft",
      "jobs.homeInsulation": "Hausdämmung",
      "jobs.allLevels": "Alle Stufen",
      "jobs.beginner": "Anfänger",
      "jobs.intermediate": "Mittelstufe",
      "jobs.advanced": "Fortgeschritten",
      "jobs.showing": "Zeigt",
      "jobs.of": "von",
      "jobs.jobsText": "Jobs",
      "jobs.time": "Zeit",
      "jobs.minutes": "Minuten",
      "jobs.credits": "Credits",
      "jobs.climateImpact": "Klimaauswirkung",
      "jobs.viewDetails": "Details & Training Anzeigen",
      "jobs.noMatch": "Keine Jobs stimmen mit Ihren Filtern überein. Versuchen Sie, sie anzupassen.",
      "profile.title": "Profileinstellungen",
      "profile.subtitle": "Verwalten Sie Ihre Kontoinformationen und Einstellungen",
      "profile.jobsCompleted": "Abgeschlossene Jobs",
      "profile.creditsEarned": "Verdiente Credits",
      "profile.co2Impact": "kg CO₂-Auswirkung",
      "profile.profileInfo": "Profilinformationen",
      "profile.profileDesc": "Aktualisieren Sie Ihren Benutzernamen und Avatar, um Ihr Konto zu personalisieren",
      "profile.profilePicture": "Profilbild",
      "profile.uploadImage": "Bild hochladen (max 2MB)",
      "profile.uploadBtn": "Bild Hochladen",
      "profile.emailCannotChange": "Ihre E-Mail-Adresse kann nicht geändert werden",
      "profile.usernameRule": "3-20 Zeichen, nur Buchstaben, Zahlen, Unterstriche und Bindestriche",
      "profile.saveChanges": "Änderungen Speichern",
      "impact.title": "Ihr Auswirkungs-Dashboard",
      "impact.subtitle": "Verfolgen Sie Ihren Beitrag zur Klimaresilienz",
      "impact.disclaimer": "Unser Prototyp simuliert, wie Klimaresilienz-Mikrojobs sowohl wirtschaftliche als auch klimatische Vorteile generieren können. In einem echten Einsatz würde jeder Abschluss einer verifizierten Feldaktivität entsprechen.",
      "impact.jobsCompleted": "Abgeschlossene Jobs",
      "impact.microJobsFinished": "Mikrojobs abgeschlossen",
      "impact.totalCredits": "Gesamt Credits",
      "impact.creditsEarned": "Verdiente Credits",
      "impact.co2Impact": "CO₂-Auswirkung",
      "impact.estimatedOffset": "Geschätzte Kompensation",
      "impact.avgQuizScore": "Durchschn. Quiz-Punktzahl",
      "impact.learningPerformance": "Lernleistung",
      "impact.creditsByCategory": "Credits nach Kategorie",
      "impact.creditsDesc": "Gesamtanzahl verdienter Credits pro Jobkategorie",
      "impact.co2ByCategory": "CO₂-Auswirkung nach Kategorie",
      "impact.co2Desc": "Verteilung Ihrer Klimaauswirkung",
      "impact.recentCompletions": "Letzte Abschlüsse",
      "impact.recentDesc": "Ihre neuesten Mikrojob-Erfolge",
      "impact.completed": "Abgeschlossen",
      "impact.score": "Punktzahl",
      "impact.noImpact": "Noch Keine Auswirkung",
      "impact.noImpactDesc": "Beginnen Sie mit der Fertigstellung von Mikrojobs, um Ihre Auswirkung hier zu sehen!",
      "regions.title": "Europäische Prioritätsregionen",
      "regions.subtitle": "Regionen nach Klimabedarf und Ungleichheitswerten eingestuft, um die Auswirkung von Mikrojobs zu maximieren",
      "regions.regionName": "Regionsname",
      "regions.country": "Land",
      "regions.climateNeed": "Klimabedarf",
      "regions.inequality": "Ungleichheit",
      "regions.priorityScore": "Prioritätswert",
      "regions.recommendedCategory": "Empfohlene Kategorie",
      "regions.actions": "Aktionen",
      "regions.viewDetails": "Details Anzeigen",
      "regions.noData": "Keine Regionsdaten verfügbar.",
      "regions.loadError": "Fehler beim Laden der Regionen",
      "regions.high": "Hoch",
      "regions.medium": "Mittel",
      "regions.low": "Niedrig",
      "auth.appName": "GreenWorks CodeX",
      "auth.appDescription": "Melden Sie sich an, um Ihre Beiträge zur Klimaresilienz zu verfolgen",
      "auth.minChars": "Minimum 6 Zeichen",
      "auth.passwordsNoMatch": "Passwörter stimmen nicht überein",
      "jobDetail.location": "Standort",
      "jobDetail.duration": "Dauer",
      "jobDetail.reward": "Belohnung",
      "jobDetail.co2Impact": "CO₂-Auswirkung",
      "jobDetail.min": "Min",
      "jobDetail.kg": "kg",
      "jobDetail.learning": "Lernen",
      "jobDetail.learningDesc": "Vervollständigen Sie diese Schulung, bevor Sie das Quiz machen",
      "jobDetail.learningObjectives": "Lernziele:",
      "jobDetail.knowledgeQuiz": "Wissensquiz",
      "jobDetail.quizDesc": "Bestehen Sie mit 60% oder mehr, um diesen Mikrojob abzuschließen",
      "jobDetail.submitQuiz": "Quiz Einreichen",
      "jobDetail.passed": "Bestanden! Sie können diesen Job abschließen.",
      "jobDetail.notPassed": "Noch nicht ganz. Überprüfen Sie die Schulung und versuchen Sie es erneut.",
      "jobDetail.completingJob": "Job wird abgeschlossen...",
      "jobDetail.completeJob": "Job Abschließen & Verdienen",
      "jobDetail.retryQuiz": "Quiz Wiederholen",
      "jobDetail.jobNotFound": "Job nicht gefunden",
      "regionDetail.backToRegions": "Zurück zu Regionen",
      "regionDetail.coordinates": "Koordinaten",
      "regionDetail.priority": "Priorität",
      "regionDetail.aboutPriority": "Über Prioritätswerte: Der Prioritätswert dieser Region kombiniert Klimabedarf und Ungleichheit, um zu leiten, wo Klimaresilienz-Mikrojobs die höchste Auswirkung haben können. Höhere Werte zeigen Gebiete an, in denen Interventionen die bedeutendste positive Veränderung für gefährdete Gemeinschaften schaffen können, die vor Klimaherausforderungen stehen.",
      "regionDetail.impactScores": "Auswirkungswerte",
      "regionDetail.impactScoresDesc": "Bewertung von Klimabedarf und sozialer Ungleichheit",
      "regionDetail.climateNeed": "Klimabedarf",
      "regionDetail.inequality": "Ungleichheit",
      "regionDetail.priorityScore": "Prioritätswert",
      "regionDetail.networkInfo": "Netzwerkinformationen",
      "regionDetail.avgDownload": "Durchschn. Download",
      "regionDetail.avgUpload": "Durchschn. Upload",
      "regionDetail.latency": "Latenz",
      "regionDetail.networkType": "Netzwerktyp",
      "regionDetail.landCover": "Landbedeckung",
      "regionDetail.landCoverDesc": "Dominanter Landschaftstyp",
      "regionDetail.primaryClass": "Primäre Landklassifizierung",
      "regionDetail.recommendedJobs": "Empfohlene Mikrojobs",
      "regionDetail.recommendedJobsDesc": "Wirkungsvollste Kategorie für diese Region",
      "regionDetail.viewRecommended": "Empfohlene Mikrojobs Anzeigen",
      "regionDetail.dataSources": "Datenquellen",
      "regionDetail.connectivityMetrics": "Konnektivitätsmetriken",
      "regionDetail.connectivityDesc": "Bereitstellung realer Netzwerkleistungsdaten einschließlich Download-/Upload-Geschwindigkeiten und Latenzmessungen.",
      "regionDetail.landCoverClass": "Landbedeckungsklassifizierung",
      "regionDetail.landCoverClassDesc": "Bereitstellung einer detaillierten 9-Klassen-Landbedeckungsanalyse zum Verständnis regionaler Landschaftsmerkmale.",
      "regionDetail.availableJobs": "Mikrojobs",
      "regionDetail.availableJobsDesc": "Jobs in dieser Kategorie werden für maximale Wirkung in dieser Region empfohlen",
    },
    it: {
      // Navigation (Italian)
      "nav.home": "Home",
      "nav.jobs": "Micro-Lavori",
      "nav.regions": "Regioni",
      "nav.impact": "Impatto",
      "nav.profile": "Profilo",
      "auth.login": "Accedi",
      "auth.signup": "Registrati",
      "auth.email": "Email",
      "auth.password": "Password",
      "auth.confirmPassword": "Conferma password",
      "auth.username": "Nome utente",
      "auth.rememberMe": "Ricordami",
      "auth.loggingIn": "Accesso in corso...",
      "auth.creatingAccount": "Creazione account...",
      "auth.signedIn": "Connesso",
      "auth.logOut": "Disconnetti",
      "auth.signUpFree": "Registrati Gratuitamente",
      "common.welcome": "Bentornato!",
      "common.loading": "Caricamento...",
      "common.save": "Salva",
      "common.cancel": "Annulla",
      "common.delete": "Elimina",
      "common.edit": "Modifica",
      "common.search": "Cerca",
      "common.saving": "Salvataggio...",
      "common.uploading": "Caricamento...",
      "home.badge": "Azione Climatica Incontra Opportunità Economica",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Micro-lavori e apprendimento per la resilienza climatica per le comunità vulnerabili in Europa.",
      "home.welcomeAlert": "Benvenuto! Registrati o accedi per iniziare a guadagnare crediti e avere un impatto climatico.",
      "home.exploreRegions": "Esplora le Regioni Europee",
      "home.browseMicroJobs": "Sfoglia i Micro-Lavori",
      "home.viewImpact": "Visualizza Impatto",
      "home.howItWorks": "Come Funziona GreenWorks CodeX",
      "home.feature1.title": "Scopri i Micro-Lavori",
      "home.feature1.desc": "Sfoglia le opportunità di resilienza climatica in tutta Europa—dalla piantumazione di alberi alla manutenzione solare, adattate alla tua posizione e livello di competenza.",
      "home.feature2.title": "Impara & Guadagna",
      "home.feature2.desc": "Completa moduli di micro-apprendimento con quiz interattivi. Supera il quiz per sbloccare il completamento del lavoro e guadagnare crediti.",
      "home.feature3.title": "Traccia il Tuo Impatto",
      "home.feature3.desc": "Monitora i tuoi crediti guadagnati e la compensazione stimata di CO₂ sul tuo pannello di impatto personale. Guarda crescere il tuo contributo.",
      "home.stat1": "Micro-Lavori Disponibili",
      "home.stat2": "Ubicazioni Europee",
      "home.stat3": "kg Potenziale di Impatto CO₂",
      "home.ctaTitle": "Pronto a Fare un Impatto?",
      "home.ctaDescLoggedIn": "Continua il tuo viaggio verso un futuro più sostenibile guadagnando ricompense economiche.",
      "home.ctaDescLoggedOut": "Unisciti a GreenWorks CodeX oggi e inizia il tuo viaggio verso un futuro più sostenibile guadagnando ricompense economiche.",
      "home.browseAvailableJobs": "Sfoglia Lavori Disponibili",
      "home.exploreRegionsBtn": "Esplora le Regioni",
      "jobs.title": "Micro-Lavori Climatici",
      "jobs.subtitle": "Scopri opportunità per costruire la resilienza climatica e guadagnare ricompense",
      "jobs.allCategories": "Tutte le Categorie",
      "jobs.treePlanting": "Piantumazione di Alberi",
      "jobs.solarMaintenance": "Manutenzione Solare",
      "jobs.waterHarvesting": "Raccolta dell'Acqua",
      "jobs.agroforestry": "Agroforestazione",
      "jobs.homeInsulation": "Isolamento Domestico",
      "jobs.allLevels": "Tutti i Livelli",
      "jobs.beginner": "Principiante",
      "jobs.intermediate": "Intermedio",
      "jobs.advanced": "Avanzato",
      "jobs.showing": "Mostrando",
      "jobs.of": "di",
      "jobs.jobsText": "lavori",
      "jobs.time": "Tempo",
      "jobs.minutes": "minuti",
      "jobs.credits": "crediti",
      "jobs.climateImpact": "Impatto climatico",
      "jobs.viewDetails": "Visualizza Dettagli e Formazione",
      "jobs.noMatch": "Nessun lavoro corrisponde ai tuoi filtri. Prova a regolarli.",
      "profile.title": "Impostazioni del Profilo",
      "profile.subtitle": "Gestisci le informazioni del tuo account e le preferenze",
      "profile.jobsCompleted": "Lavori Completati",
      "profile.creditsEarned": "Crediti Guadagnati",
      "profile.co2Impact": "kg Impatto CO₂",
      "profile.profileInfo": "Informazioni del Profilo",
      "profile.profileDesc": "Aggiorna il tuo nome utente e avatar per personalizzare il tuo account",
      "profile.profilePicture": "Immagine del Profilo",
      "profile.uploadImage": "Carica un'immagine (max 2MB)",
      "profile.uploadBtn": "Carica Immagine",
      "profile.emailCannotChange": "Il tuo indirizzo email non può essere modificato",
      "profile.usernameRule": "3-20 caratteri, solo lettere, numeri, trattini bassi e trattini",
      "profile.saveChanges": "Salva Modifiche",
      "impact.title": "Il Tuo Pannello di Impatto",
      "impact.subtitle": "Traccia il tuo contributo alla resilienza climatica",
      "impact.disclaimer": "Il nostro prototipo simula come i micro-lavori di resilienza climatica possono generare sia benefici economici che climatici. In un'implementazione reale, ogni completamento corrisponderebbe a un'attività verificata sul campo.",
      "impact.jobsCompleted": "Lavori Completati",
      "impact.microJobsFinished": "Micro-lavori terminati",
      "impact.totalCredits": "Crediti Totali",
      "impact.creditsEarned": "Crediti guadagnati",
      "impact.co2Impact": "Impatto CO₂",
      "impact.estimatedOffset": "Compensazione stimata",
      "impact.avgQuizScore": "Punteggio Medio Quiz",
      "impact.learningPerformance": "Prestazione di apprendimento",
      "impact.creditsByCategory": "Crediti per Categoria",
      "impact.creditsDesc": "Totale crediti guadagnati per categoria di lavoro",
      "impact.co2ByCategory": "Impatto CO₂ per Categoria",
      "impact.co2Desc": "Distribuzione del tuo impatto climatico",
      "impact.recentCompletions": "Completamenti Recenti",
      "impact.recentDesc": "I tuoi ultimi successi nei micro-lavori",
      "impact.completed": "Completato",
      "impact.score": "punteggio",
      "impact.noImpact": "Ancora Nessun Impatto",
      "impact.noImpactDesc": "Inizia a completare micro-lavori per vedere il tuo impatto qui!",
      "regions.title": "Regioni Prioritarie Europee",
      "regions.subtitle": "Regioni classificate per necessità climatica e punteggi di disuguaglianza per massimizzare l'impatto dei micro-lavori",
      "regions.regionName": "Nome della Regione",
      "regions.country": "Paese",
      "regions.climateNeed": "Necessità Climatica",
      "regions.inequality": "Disuguaglianza",
      "regions.priorityScore": "Punteggio di Priorità",
      "regions.recommendedCategory": "Categoria Raccomandata",
      "regions.actions": "Azioni",
      "regions.viewDetails": "Visualizza Dettagli",
      "regions.noData": "Nessun dato sulle regioni disponibile.",
      "regions.loadError": "Impossibile caricare le regioni",
      "regions.high": "Alto",
      "regions.medium": "Medio",
      "regions.low": "Basso",
      "auth.appName": "GreenWorks CodeX",
      "auth.appDescription": "Accedi per tracciare i tuoi contributi alla resilienza climatica",
      "auth.minChars": "Minimo 6 caratteri",
      "auth.passwordsNoMatch": "Le password non corrispondono",
      "jobDetail.location": "Posizione",
      "jobDetail.duration": "Durata",
      "jobDetail.reward": "Ricompensa",
      "jobDetail.co2Impact": "Impatto CO₂",
      "jobDetail.min": "min",
      "jobDetail.kg": "kg",
      "jobDetail.learning": "Apprendimento",
      "jobDetail.learningDesc": "Completa questa formazione prima di fare il quiz",
      "jobDetail.learningObjectives": "Obiettivi di Apprendimento:",
      "jobDetail.knowledgeQuiz": "Quiz di Conoscenza",
      "jobDetail.quizDesc": "Supera con il 60% o più per completare questo micro-lavoro",
      "jobDetail.submitQuiz": "Invia Quiz",
      "jobDetail.passed": "Superato! Puoi completare questo lavoro.",
      "jobDetail.notPassed": "Non ancora. Rivedi la formazione e riprova.",
      "jobDetail.completingJob": "Completamento lavoro...",
      "jobDetail.completeJob": "Completa Lavoro e Guadagna",
      "jobDetail.retryQuiz": "Riprova Quiz",
      "jobDetail.jobNotFound": "Lavoro non trovato",
      "regionDetail.backToRegions": "Torna alle Regioni",
      "regionDetail.coordinates": "Coordinate",
      "regionDetail.priority": "Priorità",
      "regionDetail.aboutPriority": "Informazioni sui Punteggi di Priorità: Il punteggio di priorità di questa regione combina necessità climatica e disuguaglianza per guidare dove i micro-lavori di resilienza climatica possono avere il massimo impatto. Punteggi più alti indicano aree dove gli interventi possono creare il cambiamento positivo più significativo per le comunità vulnerabili che affrontano sfide climatiche.",
      "regionDetail.impactScores": "Punteggi di Impatto",
      "regionDetail.impactScoresDesc": "Valutazione della necessità climatica e disuguaglianza sociale",
      "regionDetail.climateNeed": "Necessità Climatica",
      "regionDetail.inequality": "Disuguaglianza",
      "regionDetail.priorityScore": "Punteggio di Priorità",
      "regionDetail.networkInfo": "Informazioni di Rete",
      "regionDetail.avgDownload": "Download Medio",
      "regionDetail.avgUpload": "Upload Medio",
      "regionDetail.latency": "Latenza",
      "regionDetail.networkType": "Tipo di Rete",
      "regionDetail.landCover": "Copertura del Suolo",
      "regionDetail.landCoverDesc": "Tipo di paesaggio dominante",
      "regionDetail.primaryClass": "Classificazione primaria del terreno",
      "regionDetail.recommendedJobs": "Micro-Lavori Raccomandati",
      "regionDetail.recommendedJobsDesc": "Categoria più impattante per questa regione",
      "regionDetail.viewRecommended": "Visualizza Micro-Lavori Raccomandati",
      "regionDetail.dataSources": "Fonti dei Dati",
      "regionDetail.connectivityMetrics": "Metriche di Connettività",
      "regionDetail.connectivityDesc": "fornendo dati sulle prestazioni di rete del mondo reale inclusi velocità di download/upload e misurazioni di latenza.",
      "regionDetail.landCoverClass": "Classificazione della Copertura del Suolo",
      "regionDetail.landCoverClassDesc": "offrendo un'analisi dettagliata della copertura del suolo a 9 classi per comprendere le caratteristiche del paesaggio regionale.",
      "regionDetail.availableJobs": "Micro-Lavori",
      "regionDetail.availableJobsDesc": "I lavori in questa categoria sono raccomandati per il massimo impatto in questa regione",
    },
  };

  return translations[lang] || translations.en;
};
