import { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "sq" | "es" | "fr" | "de" | "it";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translations = getTranslations(language);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

const getTranslations = (lang: Language): Record<string, string> => {
  const translations: Record<Language, Record<string, string>> = {
    en: {
      // Navigation
      "nav.home": "Home",
      "nav.jobs": "Micro-Jobs",
      "nav.regions": "Regions",
      "nav.impact": "Impact",
      "nav.profile": "Profile",
      "auth.login": "Login",
      "auth.signup": "Sign Up",
      "auth.email": "Email",
      "auth.password": "Password",
      "auth.confirmPassword": "Confirm Password",
      "auth.username": "Username",
      "auth.rememberMe": "Remember me",
      "auth.loggingIn": "Logging in...",
      "auth.creatingAccount": "Creating account...",
      "auth.signedIn": "Signed in",
      "auth.logOut": "Log out",
      "auth.signUpFree": "Sign Up Free",
      "common.welcome": "Welcome back!",
      "common.loading": "Loading...",
      "common.save": "Save",
      "common.cancel": "Cancel",
      "common.delete": "Delete",
      "common.edit": "Edit",
      "common.search": "Search",
      "common.saving": "Saving...",
      "common.uploading": "Uploading...",
      "home.badge": "Climate Action Meets Economic Opportunity",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Climate-resilience micro-jobs and learning for vulnerable communities in Europe.",
      "home.welcomeAlert": "Welcome! Sign up or log in to start earning credits and making a climate impact.",
      "home.exploreRegions": "Explore European Regions",
      "home.browseMicroJobs": "Browse Micro-Jobs",
      "home.viewImpact": "View Impact",
      "home.howItWorks": "How GreenWorks CodeX Works",
      "home.feature1.title": "Discover Micro-Jobs",
      "home.feature1.desc": "Browse climate-resilience opportunities across Europe—from tree planting to solar maintenance, tailored to your location and skill level.",
      "home.feature2.title": "Learn & Earn",
      "home.feature2.desc": "Complete micro-learning modules with interactive quizzes. Pass the quiz to unlock job completion and earn credits.",
      "home.feature3.title": "Track Your Impact",
      "home.feature3.desc": "Monitor your earned credits and estimated CO₂ offset on your personal impact dashboard. See your contribution grow.",
      "home.stat1": "Micro-Jobs Available",
      "home.stat2": "European Locations",
      "home.stat3": "kg CO₂ Impact Potential",
      "home.ctaTitle": "Ready to Make an Impact?",
      "home.ctaDescLoggedIn": "Continue your journey towards a more sustainable future while earning economic rewards.",
      "home.ctaDescLoggedOut": "Join GreenWorks CodeX today and start your journey towards a more sustainable future while earning economic rewards.",
      "home.browseAvailableJobs": "Browse Available Jobs",
      "home.exploreRegionsBtn": "Explore Regions",
      "jobs.title": "Climate Micro-Jobs",
      "jobs.subtitle": "Discover opportunities to build climate resilience and earn rewards",
      "jobs.allCategories": "All Categories",
      "jobs.treePlanting": "Tree Planting",
      "jobs.solarMaintenance": "Solar Maintenance",
      "jobs.waterHarvesting": "Water Harvesting",
      "jobs.agroforestry": "Agroforestry",
      "jobs.homeInsulation": "Home Insulation",
      "jobs.allLevels": "All Levels",
      "jobs.beginner": "Beginner",
      "jobs.intermediate": "Intermediate",
      "jobs.advanced": "Advanced",
      "jobs.showing": "Showing",
      "jobs.of": "of",
      "jobs.jobsText": "jobs",
      "jobs.time": "Time",
      "jobs.minutes": "minutes",
      "jobs.credits": "credits",
      "jobs.climateImpact": "Climate impact",
      "jobs.viewDetails": "View Details & Training",
      "jobs.noMatch": "No jobs match your filters. Try adjusting them.",
      "profile.title": "Profile Settings",
      "profile.subtitle": "Manage your account information and preferences",
      "profile.jobsCompleted": "Jobs Completed",
      "profile.creditsEarned": "Credits Earned",
      "profile.co2Impact": "kg CO₂ Impact",
      "profile.profileInfo": "Profile Information",
      "profile.profileDesc": "Update your username and avatar to personalize your account",
      "profile.profilePicture": "Profile Picture",
      "profile.uploadImage": "Upload an image (max 2MB)",
      "profile.uploadBtn": "Upload Image",
      "profile.emailCannotChange": "Your email address cannot be changed",
      "profile.usernameRule": "3-20 characters, letters, numbers, underscores and hyphens only",
      "profile.saveChanges": "Save Changes",
      "impact.title": "Your Impact Dashboard",
      "impact.subtitle": "Track your contribution to climate resilience",
      "impact.disclaimer": "Our prototype simulates how climate-resilience micro-jobs can generate both economic and climate benefits. In a real deployment, each completion would correspond to verified field activity.",
      "impact.jobsCompleted": "Jobs Completed",
      "impact.microJobsFinished": "Micro-jobs finished",
      "impact.totalCredits": "Total Credits",
      "impact.creditsEarned": "Credits earned",
      "impact.co2Impact": "CO₂ Impact",
      "impact.estimatedOffset": "Estimated offset",
      "impact.avgQuizScore": "Avg Quiz Score",
      "impact.learningPerformance": "Learning performance",
      "impact.creditsByCategory": "Credits by Category",
      "impact.creditsDesc": "Total credits earned per job category",
      "impact.co2ByCategory": "CO₂ Impact by Category",
      "impact.co2Desc": "Distribution of your climate impact",
      "impact.recentCompletions": "Recent Completions",
      "impact.recentDesc": "Your latest micro-job achievements",
      "impact.completed": "Completed",
      "impact.score": "score",
      "impact.noImpact": "No Impact Yet",
      "impact.noImpactDesc": "Start completing micro-jobs to see your impact here!",
    },
    sq: {
      "nav.home": "Ballina",
      "nav.jobs": "Mikro-Punët",
      "nav.regions": "Rajonet",
      "nav.impact": "Ndikimi",
      "nav.profile": "Profili",
      "auth.login": "Hyrje",
      "auth.signup": "Regjistrohu",
      "auth.email": "Email",
      "auth.password": "Fjalëkalimi",
      "auth.confirmPassword": "Konfirmo Fjalëkalimin",
      "auth.username": "Emri i përdoruesit",
      "auth.rememberMe": "Më kujto",
      "auth.loggingIn": "Duke u futur...",
      "auth.creatingAccount": "Duke krijuar llogarinë...",
      "auth.signedIn": "I kyqur",
      "auth.logOut": "Dil",
      "auth.signUpFree": "Regjistrohu Falas",
      "common.welcome": "Mirë se erdhe përsëri!",
      "common.loading": "Duke u ngarkuar...",
      "common.save": "Ruaj",
      "common.cancel": "Anulo",
      "common.delete": "Fshi",
      "common.edit": "Ndrysho",
      "common.search": "Kërko",
      "common.saving": "Duke ruajtur...",
      "common.uploading": "Duke ngarkuar...",
      "home.badge": "Veprimi Klimatik Takohet me Mundësinë Ekonomike",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Mikro-punë dhe mësim për qëndrueshmërinë klimatike për komunitetet e cenueshme në Evropë.",
      "home.welcomeAlert": "Mirë se vini! Regjistrohuni ose hyni për të filluar të fitoni kredite dhe të bëni ndikim klimatik.",
      "home.exploreRegions": "Eksploro Rajonet Evropiane",
      "home.browseMicroJobs": "Shfleto Mikro-Punët",
      "home.viewImpact": "Shiko Ndikimin",
      "home.howItWorks": "Si Funksionon GreenWorks CodeX",
      "home.feature1.title": "Zbullo Mikro-Punët",
      "home.feature1.desc": "Shfleto mundësitë për qëndrueshmëri klimatike në të gjithë Evropën—nga mbjellja e pemëve tek mirëmbajtja diellore, të përshtatura për vendndodhjen dhe nivelin tënd të aftësive.",
      "home.feature2.title": "Mëso & Fito",
      "home.feature2.desc": "Plotëso module mikro-mësimi me kuize interaktive. Kalo kuizin për të zhbllokuar përfundimin e punës dhe për të fituar kredite.",
      "home.feature3.title": "Gjurmo Ndikimin Tënd",
      "home.feature3.desc": "Monitoroni kreditë tuaja të fituara dhe kompenimin e përllogaritur të CO₂ në panelin tuaj personal të ndikimit. Shihni kontributin tuaj të rritet.",
      "home.stat1": "Mikro-Punë të Disponueshme",
      "home.stat2": "Vendndodhje Evropiane",
      "home.stat3": "kg Potencial Ndikimi CO₂",
      "home.ctaTitle": "Gati për të Bërë Ndikim?",
      "home.ctaDescLoggedIn": "Vazhdo udhëtimin tënd drejt një të ardhmeje më të qëndrueshme duke fituar shpërblime ekonomike.",
      "home.ctaDescLoggedOut": "Bashkohuni me GreenWorks CodeX sot dhe filloni udhëtimin tuaj drejt një të ardhmeje më të qëndrueshme duke fituar shpërblime ekonomike.",
      "home.browseAvailableJobs": "Shfleto Punët e Disponueshme",
      "home.exploreRegionsBtn": "Eksploro Rajonet",
      "jobs.title": "Mikro-Punë Klimatike",
      "jobs.subtitle": "Zbullo mundësi për të ndërtuar qëndrueshmëri klimatike dhe për të fituar shpërblime",
      "jobs.allCategories": "Të Gjitha Kategoritë",
      "jobs.treePlanting": "Mbjell je Pemësh",
      "jobs.solarMaintenance": "Mirëmbajtje Diellore",
      "jobs.waterHarvesting": "Grumbullim i Ujit",
      "jobs.agroforestry": "Agropylltari",
      "jobs.homeInsulation": "Izolim i Shtëpisë",
      "jobs.allLevels": "Të Gjitha Nivelet",
      "jobs.beginner": "Fillestar",
      "jobs.intermediate": "Mesatar",
      "jobs.advanced": "I Avancuar",
      "jobs.showing": "Duke treguar",
      "jobs.of": "nga",
      "jobs.jobsText": "punë",
      "jobs.time": "Kohëzgjatja",
      "jobs.minutes": "minuta",
      "jobs.credits": "kredite",
      "jobs.climateImpact": "Ndikimi klimatik",
      "jobs.viewDetails": "Shiko Detajet & Trajnimin",
      "jobs.noMatch": "Asnjë punë nuk përputhet me filtrat tuaj. Provo t'i rregullosh ato.",
      "profile.title": "Cilësimet e Profilit",
      "profile.subtitle": "Menaxho informacionin e llogarisë dhe preferencat",
      "profile.jobsCompleted": "Punë të Përfunduara",
      "profile.creditsEarned": "Kredite të Fituara",
      "profile.co2Impact": "kg Ndikim CO₂",
      "profile.profileInfo": "Informacioni i Profilit",
      "profile.profileDesc": "Përditëso emrin e përdoruesit dhe avatarin për të personalizuar llogarinë",
      "profile.profilePicture": "Fotografia e Profilit",
      "profile.uploadImage": "Ngarko një imazh (maks 2MB)",
      "profile.uploadBtn": "Ngarko Imazhin",
      "profile.emailCannotChange": "Adresa juaj e emailit nuk mund të ndryshohet",
      "profile.usernameRule": "3-20 karaktere, vetëm shkronja, numra, nënviza dhe viza",
      "profile.saveChanges": "Ruaj Ndryshimet",
      "impact.title": "Paneli Juaj i Ndikimit",
      "impact.subtitle": "Gjurmoni kontributin tuaj për qëndrueshmërinë klimatike",
      "impact.disclaimer": "Prototipi ynë simulon se si mikro-punët e qëndrueshmërisë klimatike mund të gjenerojnë përfitime ekonomike dhe klimatike. Në një aplikim real, çdo përfundim do të korrespondonte me aktivitet të verifikuar në terren.",
      "impact.jobsCompleted": "Punë të Përfunduara",
      "impact.microJobsFinished": "Mikro-punë të përfunduara",
      "impact.totalCredits": "Kredite Totale",
      "impact.creditsEarned": "Kredite të fituara",
      "impact.co2Impact": "Ndikimi CO₂",
      "impact.estimatedOffset": "Kompensim i përllogaritur",
      "impact.avgQuizScore": "Rezultat Mesatar Kuizi",
      "impact.learningPerformance": "Performanca e të mësuarit",
      "impact.creditsByCategory": "Kredite sipas Kategorisë",
      "impact.creditsDesc": "Totali i krediteve të fituara për kategori pune",
      "impact.co2ByCategory": "Ndikimi CO₂ sipas Kategorisë",
      "impact.co2Desc": "Shpërndarja e ndikimit tuaj klimatik",
      "impact.recentCompletions": "Përfundimet e Fundit",
      "impact.recentDesc": "Arritjet tuaja më të fundit në mikro-punë",
      "impact.completed": "U përfundua",
      "impact.score": "rezultat",
      "impact.noImpact": "Ende Pa Ndikim",
      "impact.noImpactDesc": "Filloni të përfundoni mikro-punë për të parë ndikimin tuaj këtu!",
    },
    es: {
      // Navigation (Spanish)
      "nav.home": "Inicio",
      "nav.jobs": "Micro-Trabajos",
      "nav.regions": "Regiones",
      "nav.impact": "Impacto",
      "nav.profile": "Perfil",
      "auth.login": "Iniciar sesión",
      "auth.signup": "Registrarse",
      "auth.email": "Correo electrónico",
      "auth.password": "Contraseña",
      "auth.confirmPassword": "Confirmar contraseña",
      "auth.username": "Nombre de usuario",
      "auth.rememberMe": "Recuérdame",
      "auth.loggingIn": "Iniciando sesión...",
      "auth.creatingAccount": "Creando cuenta...",
      "auth.signedIn": "Sesión iniciada",
      "auth.logOut": "Cerrar sesión",
      "auth.signUpFree": "Registrarse Gratis",
      "common.welcome": "¡Bienvenido de nuevo!",
      "common.loading": "Cargando...",
      "common.save": "Guardar",
      "common.cancel": "Cancelar",
      "common.delete": "Eliminar",
      "common.edit": "Editar",
      "common.search": "Buscar",
      "common.saving": "Guardando...",
      "common.uploading": "Subiendo...",
      "home.badge": "Acción Climática se Encuentra con Oportunidad Económica",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Micro-trabajos y aprendizaje de resiliencia climática para comunidades vulnerables en Europa.",
      "home.welcomeAlert": "¡Bienvenido! Regístrate o inicia sesión para comenzar a ganar créditos y hacer un impacto climático.",
      "home.exploreRegions": "Explorar Regiones Europeas",
      "home.browseMicroJobs": "Navegar Micro-Trabajos",
      "home.viewImpact": "Ver Impacto",
      "home.howItWorks": "Cómo Funciona GreenWorks CodeX",
      "home.feature1.title": "Descubre Micro-Trabajos",
      "home.feature1.desc": "Explora oportunidades de resiliencia climática en Europa, desde plantar árboles hasta mantenimiento solar, adaptadas a tu ubicación y nivel de habilidad.",
      "home.feature2.title": "Aprende & Gana",
      "home.feature2.desc": "Completa módulos de micro-aprendizaje con cuestionarios interactivos. Aprueba el cuestionario para desbloquear la finalización del trabajo y ganar créditos.",
      "home.feature3.title": "Rastrea Tu Impacto",
      "home.feature3.desc": "Monitorea tus créditos ganados y la compensación estimada de CO₂ en tu panel de impacto personal. Ve crecer tu contribución.",
      "home.stat1": "Micro-Trabajos Disponibles",
      "home.stat2": "Ubicaciones Europeas",
      "home.stat3": "kg de Potencial de Impacto CO₂",
      "home.ctaTitle": "¿Listo para Hacer un Impacto?",
      "home.ctaDescLoggedIn": "Continúa tu viaje hacia un futuro más sostenible mientras ganas recompensas económicas.",
      "home.ctaDescLoggedOut": "Únete a GreenWorks CodeX hoy y comienza tu viaje hacia un futuro más sostenible mientras ganas recompensas económicas.",
      "home.browseAvailableJobs": "Navegar Trabajos Disponibles",
      "home.exploreRegionsBtn": "Explorar Regiones",
      "jobs.title": "Micro-Trabajos Climáticos",
      "jobs.subtitle": "Descubre oportunidades para construir resiliencia climática y ganar recompensas",
      "jobs.allCategories": "Todas las Categorías",
      "jobs.treePlanting": "Plantación de Árboles",
      "jobs.solarMaintenance": "Mantenimiento Solar",
      "jobs.waterHarvesting": "Recolección de Agua",
      "jobs.agroforestry": "Agroforestería",
      "jobs.homeInsulation": "Aislamiento del Hogar",
      "jobs.allLevels": "Todos los Niveles",
      "jobs.beginner": "Principiante",
      "jobs.intermediate": "Intermedio",
      "jobs.advanced": "Avanzado",
      "jobs.showing": "Mostrando",
      "jobs.of": "de",
      "jobs.jobsText": "trabajos",
      "jobs.time": "Tiempo",
      "jobs.minutes": "minutos",
      "jobs.credits": "créditos",
      "jobs.climateImpact": "Impacto climático",
      "jobs.viewDetails": "Ver Detalles y Capacitación",
      "jobs.noMatch": "Ningún trabajo coincide con tus filtros. Intenta ajustarlos.",
      "profile.title": "Configuración del Perfil",
      "profile.subtitle": "Gestiona la información de tu cuenta y preferencias",
      "profile.jobsCompleted": "Trabajos Completados",
      "profile.creditsEarned": "Créditos Ganados",
      "profile.co2Impact": "kg de Impacto CO₂",
      "profile.profileInfo": "Información del Perfil",
      "profile.profileDesc": "Actualiza tu nombre de usuario y avatar para personalizar tu cuenta",
      "profile.profilePicture": "Foto de Perfil",
      "profile.uploadImage": "Sube una imagen (máx 2MB)",
      "profile.uploadBtn": "Subir Imagen",
      "profile.emailCannotChange": "Tu dirección de correo electrónico no se puede cambiar",
      "profile.usernameRule": "3-20 caracteres, solo letras, números, guiones bajos y guiones",
      "profile.saveChanges": "Guardar Cambios",
      "impact.title": "Tu Panel de Impacto",
      "impact.subtitle": "Rastrea tu contribución a la resiliencia climática",
      "impact.disclaimer": "Nuestro prototipo simula cómo los micro-trabajos de resiliencia climática pueden generar beneficios económicos y climáticos. En una implementación real, cada finalización correspondería a actividad verificada en campo.",
      "impact.jobsCompleted": "Trabajos Completados",
      "impact.microJobsFinished": "Micro-trabajos terminados",
      "impact.totalCredits": "Créditos Totales",
      "impact.creditsEarned": "Créditos ganados",
      "impact.co2Impact": "Impacto CO₂",
      "impact.estimatedOffset": "Compensación estimada",
      "impact.avgQuizScore": "Puntuación Promedio del Cuestionario",
      "impact.learningPerformance": "Rendimiento de aprendizaje",
      "impact.creditsByCategory": "Créditos por Categoría",
      "impact.creditsDesc": "Total de créditos ganados por categoría de trabajo",
      "impact.co2ByCategory": "Impacto CO₂ por Categoría",
      "impact.co2Desc": "Distribución de tu impacto climático",
      "impact.recentCompletions": "Finalizaciones Recientes",
      "impact.recentDesc": "Tus últimos logros en micro-trabajos",
      "impact.completed": "Completado",
      "impact.score": "puntuación",
      "impact.noImpact": "Aún Sin Impacto",
      "impact.noImpactDesc": "¡Comienza a completar micro-trabajos para ver tu impacto aquí!",
    },
    fr: {
      // Navigation (French)
      "nav.home": "Accueil",
      "nav.jobs": "Micro-Emplois",
      "nav.regions": "Régions",
      "nav.impact": "Impact",
      "nav.profile": "Profil",
      "auth.login": "Connexion",
      "auth.signup": "S'inscrire",
      "auth.email": "Email",
      "auth.password": "Mot de passe",
      "auth.confirmPassword": "Confirmer le mot de passe",
      "auth.username": "Nom d'utilisateur",
      "auth.rememberMe": "Se souvenir de moi",
      "auth.loggingIn": "Connexion en cours...",
      "auth.creatingAccount": "Création du compte...",
      "auth.signedIn": "Connecté",
      "auth.logOut": "Se déconnecter",
      "auth.signUpFree": "S'inscrire Gratuitement",
      "common.welcome": "Bon retour!",
      "common.loading": "Chargement...",
      "common.save": "Enregistrer",
      "common.cancel": "Annuler",
      "common.delete": "Supprimer",
      "common.edit": "Modifier",
      "common.search": "Rechercher",
      "common.saving": "Enregistrement...",
      "common.uploading": "Téléchargement...",
      "home.badge": "L'action Climatique Rencontre l'Opportunité Économique",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Micro-emplois et apprentissage de résilience climatique pour les communautés vulnérables en Europe.",
      "home.welcomeAlert": "Bienvenue! Inscrivez-vous ou connectez-vous pour commencer à gagner des crédits et avoir un impact climatique.",
      "home.exploreRegions": "Explorer les Régions Européennes",
      "home.browseMicroJobs": "Parcourir les Micro-Emplois",
      "home.viewImpact": "Voir l'Impact",
      "home.howItWorks": "Comment Fonctionne GreenWorks CodeX",
      "home.feature1.title": "Découvrir les Micro-Emplois",
      "home.feature1.desc": "Parcourez les opportunités de résilience climatique en Europe—de la plantation d'arbres à l'entretien solaire, adaptées à votre emplacement et niveau de compétence.",
      "home.feature2.title": "Apprendre & Gagner",
      "home.feature2.desc": "Complétez des modules de micro-apprentissage avec des quiz interactifs. Réussissez le quiz pour déverrouiller l'achèvement du travail et gagner des crédits.",
      "home.feature3.title": "Suivre Votre Impact",
      "home.feature3.desc": "Surveillez vos crédits gagnés et la compensation estimée en CO₂ sur votre tableau de bord d'impact personnel. Voyez votre contribution grandir.",
      "home.stat1": "Micro-Emplois Disponibles",
      "home.stat2": "Emplacements Européens",
      "home.stat3": "kg de Potentiel d'Impact CO₂",
      "home.ctaTitle": "Prêt à Faire un Impact?",
      "home.ctaDescLoggedIn": "Continuez votre voyage vers un avenir plus durable tout en gagnant des récompenses économiques.",
      "home.ctaDescLoggedOut": "Rejoignez GreenWorks CodeX aujourd'hui et commencez votre voyage vers un avenir plus durable tout en gagnant des récompenses économiques.",
      "home.browseAvailableJobs": "Parcourir les Emplois Disponibles",
      "home.exploreRegionsBtn": "Explorer les Régions",
      "jobs.title": "Micro-Emplois Climatiques",
      "jobs.subtitle": "Découvrez des opportunités pour bâtir la résilience climatique et gagner des récompenses",
      "jobs.allCategories": "Toutes les Catégories",
      "jobs.treePlanting": "Plantation d'Arbres",
      "jobs.solarMaintenance": "Entretien Solaire",
      "jobs.waterHarvesting": "Collecte d'Eau",
      "jobs.agroforestry": "Agroforesterie",
      "jobs.homeInsulation": "Isolation de la Maison",
      "jobs.allLevels": "Tous les Niveaux",
      "jobs.beginner": "Débutant",
      "jobs.intermediate": "Intermédiaire",
      "jobs.advanced": "Avancé",
      "jobs.showing": "Affichage",
      "jobs.of": "de",
      "jobs.jobsText": "emplois",
      "jobs.time": "Durée",
      "jobs.minutes": "minutes",
      "jobs.credits": "crédits",
      "jobs.climateImpact": "Impact climatique",
      "jobs.viewDetails": "Voir Détails et Formation",
      "jobs.noMatch": "Aucun emploi ne correspond à vos filtres. Essayez de les ajuster.",
      "profile.title": "Paramètres du Profil",
      "profile.subtitle": "Gérez les informations de votre compte et vos préférences",
      "profile.jobsCompleted": "Emplois Terminés",
      "profile.creditsEarned": "Crédits Gagnés",
      "profile.co2Impact": "kg d'Impact CO₂",
      "profile.profileInfo": "Informations du Profil",
      "profile.profileDesc": "Mettez à jour votre nom d'utilisateur et votre avatar pour personnaliser votre compte",
      "profile.profilePicture": "Photo de Profil",
      "profile.uploadImage": "Télécharger une image (max 2 Mo)",
      "profile.uploadBtn": "Télécharger l'Image",
      "profile.emailCannotChange": "Votre adresse e-mail ne peut pas être modifiée",
      "profile.usernameRule": "3-20 caractères, lettres, chiffres, tirets bas et traits d'union uniquement",
      "profile.saveChanges": "Enregistrer les Modifications",
      "impact.title": "Votre Tableau de Bord d'Impact",
      "impact.subtitle": "Suivez votre contribution à la résilience climatique",
      "impact.disclaimer": "Notre prototype simule comment les micro-emplois de résilience climatique peuvent générer à la fois des avantages économiques et climatiques. Dans un déploiement réel, chaque achèvement correspondrait à une activité vérifiée sur le terrain.",
      "impact.jobsCompleted": "Emplois Terminés",
      "impact.microJobsFinished": "Micro-emplois terminés",
      "impact.totalCredits": "Crédits Totaux",
      "impact.creditsEarned": "Crédits gagnés",
      "impact.co2Impact": "Impact CO₂",
      "impact.estimatedOffset": "Compensation estimée",
      "impact.avgQuizScore": "Score Moyen du Quiz",
      "impact.learningPerformance": "Performance d'apprentissage",
      "impact.creditsByCategory": "Crédits par Catégorie",
      "impact.creditsDesc": "Total des crédits gagnés par catégorie d'emploi",
      "impact.co2ByCategory": "Impact CO₂ par Catégorie",
      "impact.co2Desc": "Distribution de votre impact climatique",
      "impact.recentCompletions": "Achèvements Récents",
      "impact.recentDesc": "Vos dernières réalisations en micro-emplois",
      "impact.completed": "Terminé",
      "impact.score": "score",
      "impact.noImpact": "Pas Encore d'Impact",
      "impact.noImpactDesc": "Commencez à terminer des micro-emplois pour voir votre impact ici!",
    },
    de: {
      // Navigation (German)
      "nav.home": "Startseite",
      "nav.jobs": "Jobs",
      "nav.regions": "Regionen",
      "nav.impact": "Auswirkung",
      "nav.profile": "Profil",
      "auth.login": "Anmelden",
      "auth.signup": "Registrieren",
      "auth.email": "E-Mail",
      "auth.password": "Passwort",
      "auth.confirmPassword": "Passwort bestätigen",
      "auth.username": "Benutzername",
      "auth.rememberMe": "Erinnere dich an mich",
      "auth.loggingIn": "Anmeldung läuft...",
      "auth.creatingAccount": "Konto wird erstellt...",
      "auth.signedIn": "Angemeldet",
      "auth.logOut": "Abmelden",
      "auth.signUpFree": "Kostenlos Registrieren",
      "common.welcome": "Willkommen zurück!",
      "common.loading": "Wird geladen...",
      "common.save": "Speichern",
      "common.cancel": "Abbrechen",
      "common.delete": "Löschen",
      "common.edit": "Bearbeiten",
      "common.search": "Suchen",
      "common.saving": "Speichern...",
      "common.uploading": "Hochladen...",
      "home.badge": "Klimaschutz Trifft Wirtschaftliche Chancen",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Klimaresilienz-Mikrojobs und Lernen für gefährdete Gemeinden in Europa.",
      "home.welcomeAlert": "Willkommen! Melden Sie sich an oder registrieren Sie sich, um Credits zu verdienen und klimawirksam zu werden.",
      "home.exploreRegions": "Europäische Regionen Erkunden",
      "home.browseMicroJobs": "Mikrojobs Durchsuchen",
      "home.viewImpact": "Auswirkung Anzeigen",
      "home.howItWorks": "So Funktioniert GreenWorks CodeX",
      "home.feature1.title": "Mikrojobs Entdecken",
      "home.feature1.desc": "Durchsuchen Sie Klimaresilienz-Möglichkeiten in ganz Europa—von Baumpflanzungen bis zur Solarpflege, angepasst an Ihren Standort und Ihr Qualifikationsniveau.",
      "home.feature2.title": "Lernen & Verdienen",
      "home.feature2.desc": "Absolvieren Sie Mikro-Lernmodule mit interaktiven Quiz. Bestehen Sie das Quiz, um die Jobabschluss freizuschalten und Credits zu verdienen.",
      "home.feature3.title": "Verfolgen Sie Ihre Auswirkung",
      "home.feature3.desc": "Überwachen Sie Ihre verdienten Credits und geschätzte CO₂-Kompensation auf Ihrem persönlichen Impact-Dashboard. Sehen Sie Ihren Beitrag wachsen.",
      "home.stat1": "Mikrojobs Verfügbar",
      "home.stat2": "Europäische Standorte",
      "home.stat3": "kg CO₂-Auswirkungspotenzial",
      "home.ctaTitle": "Bereit, Wirkung zu Zeigen?",
      "home.ctaDescLoggedIn": "Setzen Sie Ihre Reise zu einer nachhaltigeren Zukunft fort und verdienen Sie wirtschaftliche Belohnungen.",
      "home.ctaDescLoggedOut": "Treten Sie GreenWorks CodeX heute bei und beginnen Sie Ihre Reise zu einer nachhaltigeren Zukunft, während Sie wirtschaftliche Belohnungen verdienen.",
      "home.browseAvailableJobs": "Verfügbare Jobs Durchsuchen",
      "home.exploreRegionsBtn": "Regionen Erkunden",
      "jobs.title": "Klima-Mikrojobs",
      "jobs.subtitle": "Entdecken Sie Möglichkeiten, Klimaresilienz aufzubauen und Belohnungen zu verdienen",
      "jobs.allCategories": "Alle Kategorien",
      "jobs.treePlanting": "Baumpflanzung",
      "jobs.solarMaintenance": "Solarwartung",
      "jobs.waterHarvesting": "Wassergewinnung",
      "jobs.agroforestry": "Agroforstwirtschaft",
      "jobs.homeInsulation": "Hausdämmung",
      "jobs.allLevels": "Alle Stufen",
      "jobs.beginner": "Anfänger",
      "jobs.intermediate": "Mittelstufe",
      "jobs.advanced": "Fortgeschritten",
      "jobs.showing": "Zeigt",
      "jobs.of": "von",
      "jobs.jobsText": "Jobs",
      "jobs.time": "Zeit",
      "jobs.minutes": "Minuten",
      "jobs.credits": "Credits",
      "jobs.climateImpact": "Klimaauswirkung",
      "jobs.viewDetails": "Details & Training Anzeigen",
      "jobs.noMatch": "Keine Jobs stimmen mit Ihren Filtern überein. Versuchen Sie, sie anzupassen.",
      "profile.title": "Profileinstellungen",
      "profile.subtitle": "Verwalten Sie Ihre Kontoinformationen und Einstellungen",
      "profile.jobsCompleted": "Abgeschlossene Jobs",
      "profile.creditsEarned": "Verdiente Credits",
      "profile.co2Impact": "kg CO₂-Auswirkung",
      "profile.profileInfo": "Profilinformationen",
      "profile.profileDesc": "Aktualisieren Sie Ihren Benutzernamen und Avatar, um Ihr Konto zu personalisieren",
      "profile.profilePicture": "Profilbild",
      "profile.uploadImage": "Bild hochladen (max 2MB)",
      "profile.uploadBtn": "Bild Hochladen",
      "profile.emailCannotChange": "Ihre E-Mail-Adresse kann nicht geändert werden",
      "profile.usernameRule": "3-20 Zeichen, nur Buchstaben, Zahlen, Unterstriche und Bindestriche",
      "profile.saveChanges": "Änderungen Speichern",
      "impact.title": "Ihr Auswirkungs-Dashboard",
      "impact.subtitle": "Verfolgen Sie Ihren Beitrag zur Klimaresilienz",
      "impact.disclaimer": "Unser Prototyp simuliert, wie Klimaresilienz-Mikrojobs sowohl wirtschaftliche als auch klimatische Vorteile generieren können. In einem echten Einsatz würde jeder Abschluss einer verifizierten Feldaktivität entsprechen.",
      "impact.jobsCompleted": "Abgeschlossene Jobs",
      "impact.microJobsFinished": "Mikrojobs abgeschlossen",
      "impact.totalCredits": "Gesamt Credits",
      "impact.creditsEarned": "Verdiente Credits",
      "impact.co2Impact": "CO₂-Auswirkung",
      "impact.estimatedOffset": "Geschätzte Kompensation",
      "impact.avgQuizScore": "Durchschn. Quiz-Punktzahl",
      "impact.learningPerformance": "Lernleistung",
      "impact.creditsByCategory": "Credits nach Kategorie",
      "impact.creditsDesc": "Gesamtanzahl verdienter Credits pro Jobkategorie",
      "impact.co2ByCategory": "CO₂-Auswirkung nach Kategorie",
      "impact.co2Desc": "Verteilung Ihrer Klimaauswirkung",
      "impact.recentCompletions": "Letzte Abschlüsse",
      "impact.recentDesc": "Ihre neuesten Mikrojob-Erfolge",
      "impact.completed": "Abgeschlossen",
      "impact.score": "Punktzahl",
      "impact.noImpact": "Noch Keine Auswirkung",
      "impact.noImpactDesc": "Beginnen Sie mit der Fertigstellung von Mikrojobs, um Ihre Auswirkung hier zu sehen!",
    },
    it: {
      // Navigation (Italian)
      "nav.home": "Home",
      "nav.jobs": "Micro-Lavori",
      "nav.regions": "Regioni",
      "nav.impact": "Impatto",
      "nav.profile": "Profilo",
      "auth.login": "Accedi",
      "auth.signup": "Registrati",
      "auth.email": "Email",
      "auth.password": "Password",
      "auth.confirmPassword": "Conferma password",
      "auth.username": "Nome utente",
      "auth.rememberMe": "Ricordami",
      "auth.loggingIn": "Accesso in corso...",
      "auth.creatingAccount": "Creazione account...",
      "auth.signedIn": "Connesso",
      "auth.logOut": "Disconnetti",
      "auth.signUpFree": "Registrati Gratuitamente",
      "common.welcome": "Bentornato!",
      "common.loading": "Caricamento...",
      "common.save": "Salva",
      "common.cancel": "Annulla",
      "common.delete": "Elimina",
      "common.edit": "Modifica",
      "common.search": "Cerca",
      "common.saving": "Salvataggio...",
      "common.uploading": "Caricamento...",
      "home.badge": "Azione Climatica Incontra Opportunità Economica",
      "home.title": "GreenWorks CodeX",
      "home.subtitle": "Micro-lavori e apprendimento per la resilienza climatica per le comunità vulnerabili in Europa.",
      "home.welcomeAlert": "Benvenuto! Registrati o accedi per iniziare a guadagnare crediti e avere un impatto climatico.",
      "home.exploreRegions": "Esplora le Regioni Europee",
      "home.browseMicroJobs": "Sfoglia i Micro-Lavori",
      "home.viewImpact": "Visualizza Impatto",
      "home.howItWorks": "Come Funziona GreenWorks CodeX",
      "home.feature1.title": "Scopri i Micro-Lavori",
      "home.feature1.desc": "Sfoglia le opportunità di resilienza climatica in tutta Europa—dalla piantumazione di alberi alla manutenzione solare, adattate alla tua posizione e livello di competenza.",
      "home.feature2.title": "Impara & Guadagna",
      "home.feature2.desc": "Completa moduli di micro-apprendimento con quiz interattivi. Supera il quiz per sbloccare il completamento del lavoro e guadagnare crediti.",
      "home.feature3.title": "Traccia il Tuo Impatto",
      "home.feature3.desc": "Monitora i tuoi crediti guadagnati e la compensazione stimata di CO₂ sul tuo pannello di impatto personale. Guarda crescere il tuo contributo.",
      "home.stat1": "Micro-Lavori Disponibili",
      "home.stat2": "Ubicazioni Europee",
      "home.stat3": "kg Potenziale di Impatto CO₂",
      "home.ctaTitle": "Pronto a Fare un Impatto?",
      "home.ctaDescLoggedIn": "Continua il tuo viaggio verso un futuro più sostenibile guadagnando ricompense economiche.",
      "home.ctaDescLoggedOut": "Unisciti a GreenWorks CodeX oggi e inizia il tuo viaggio verso un futuro più sostenibile guadagnando ricompense economiche.",
      "home.browseAvailableJobs": "Sfoglia Lavori Disponibili",
      "home.exploreRegionsBtn": "Esplora le Regioni",
      "jobs.title": "Micro-Lavori Climatici",
      "jobs.subtitle": "Scopri opportunità per costruire la resilienza climatica e guadagnare ricompense",
      "jobs.allCategories": "Tutte le Categorie",
      "jobs.treePlanting": "Piantumazione di Alberi",
      "jobs.solarMaintenance": "Manutenzione Solare",
      "jobs.waterHarvesting": "Raccolta dell'Acqua",
      "jobs.agroforestry": "Agroforestazione",
      "jobs.homeInsulation": "Isolamento Domestico",
      "jobs.allLevels": "Tutti i Livelli",
      "jobs.beginner": "Principiante",
      "jobs.intermediate": "Intermedio",
      "jobs.advanced": "Avanzato",
      "jobs.showing": "Mostrando",
      "jobs.of": "di",
      "jobs.jobsText": "lavori",
      "jobs.time": "Tempo",
      "jobs.minutes": "minuti",
      "jobs.credits": "crediti",
      "jobs.climateImpact": "Impatto climatico",
      "jobs.viewDetails": "Visualizza Dettagli e Formazione",
      "jobs.noMatch": "Nessun lavoro corrisponde ai tuoi filtri. Prova a regolarli.",
      "profile.title": "Impostazioni del Profilo",
      "profile.subtitle": "Gestisci le informazioni del tuo account e le preferenze",
      "profile.jobsCompleted": "Lavori Completati",
      "profile.creditsEarned": "Crediti Guadagnati",
      "profile.co2Impact": "kg Impatto CO₂",
      "profile.profileInfo": "Informazioni del Profilo",
      "profile.profileDesc": "Aggiorna il tuo nome utente e avatar per personalizzare il tuo account",
      "profile.profilePicture": "Immagine del Profilo",
      "profile.uploadImage": "Carica un'immagine (max 2MB)",
      "profile.uploadBtn": "Carica Immagine",
      "profile.emailCannotChange": "Il tuo indirizzo email non può essere modificato",
      "profile.usernameRule": "3-20 caratteri, solo lettere, numeri, trattini bassi e trattini",
      "profile.saveChanges": "Salva Modifiche",
      "impact.title": "Il Tuo Pannello di Impatto",
      "impact.subtitle": "Traccia il tuo contributo alla resilienza climatica",
      "impact.disclaimer": "Il nostro prototipo simula come i micro-lavori di resilienza climatica possono generare sia benefici economici che climatici. In un'implementazione reale, ogni completamento corrisponderebbe a un'attività verificata sul campo.",
      "impact.jobsCompleted": "Lavori Completati",
      "impact.microJobsFinished": "Micro-lavori terminati",
      "impact.totalCredits": "Crediti Totali",
      "impact.creditsEarned": "Crediti guadagnati",
      "impact.co2Impact": "Impatto CO₂",
      "impact.estimatedOffset": "Compensazione stimata",
      "impact.avgQuizScore": "Punteggio Medio Quiz",
      "impact.learningPerformance": "Prestazione di apprendimento",
      "impact.creditsByCategory": "Crediti per Categoria",
      "impact.creditsDesc": "Totale crediti guadagnati per categoria di lavoro",
      "impact.co2ByCategory": "Impatto CO₂ per Categoria",
      "impact.co2Desc": "Distribuzione del tuo impatto climatico",
      "impact.recentCompletions": "Completamenti Recenti",
      "impact.recentDesc": "I tuoi ultimi successi nei micro-lavori",
      "impact.completed": "Completato",
      "impact.score": "punteggio",
      "impact.noImpact": "Ancora Nessun Impatto",
      "impact.noImpactDesc": "Inizia a completare micro-lavori per vedere il tuo impatto qui!",
    },
  };

  return translations[lang] || translations.en;
};
